# Generated by Django 5.0.14 on 2026-07-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_patientdocument_blood_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocument',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False once a newer version has replaced this file, or it was deleted; kept for audit history.'),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Deleted by Super Admin (spec 8: only Super Admin can delete).'),
        ),
    ]
