# Generated by Django 5.0.14 on 2026-07-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_supplier_batch_ledger'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockledger',
            new_name='pharmacy_st_medicin_139907_idx',
            old_name='pharmacy_st_medicine_3d979c_idx',
        ),
    ]
