# Generated by Django 5.0.14 on 2026-07-22 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report_type', models.CharField(choices=[('imaging_report', 'Imaging Report'), ('scan_report', 'Scan Report'), ('doppler_report', 'Doppler Report'), ('ecg_strip', 'ECG Strip'), ('echo_report', 'Echo Report'), ('density_report', 'Bone Density Report')], default='imaging_report', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_tests', to='departments.department')),
            ],
            options={
                'db_table': 'radiology_test',
                'ordering': ['name'],
            },
        ),
    ]
