# Generated by hand - no live Django in this sandbox. Run
# `makemigrations --check` after install to confirm this matches.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_expand_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='counter_name',
            field=models.CharField(
                default='Main Cash Counter', max_length=100,
                help_text='e.g. "Main Cash Counter", "Laboratory Counter", "Radiology Counter"',
            ),
        ),
        migrations.AddField(
            model_name='bill',
            name='insurance_coverage_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(
                choices=[
                    ('opd', 'OPD Billing'), ('ipd', 'IPD Billing'), ('lab', 'Lab Billing'),
                    ('radiology', 'Radiology Billing'), ('pharmacy', 'Pharmacy Billing'),
                    ('surgery', 'Surgery Billing'), ('other', 'Other'),
                ],
                default='opd', max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('cash', 'Cash'), ('esewa', 'eSewa'), ('khalti', 'Khalti'),
                    ('phonepe', 'PhonePe'), ('mobile_banking', 'Mobile Banking'),
                    ('fonepay', 'FonePay'), ('bank_transfer', 'Bank Transfer'),
                    ('card', 'Card Payment'), ('insurance', 'Insurance'),
                    ('credit', 'Credit'), ('other', 'Other'),
                ],
                max_length=15,
            ),
        ),
    ]
