# Generated by hand - no live Django in this sandbox. Run
# `makemigrations --check` after install to confirm this matches.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_bill_counter_insurance_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(
                choices=[
                    ('opd', 'OPD Billing'), ('ipd', 'IPD Billing'), ('lab', 'Lab Billing'),
                    ('radiology', 'Radiology Billing'), ('blood_bank', 'Blood Bank Billing'),
                    ('pharmacy', 'Pharmacy Billing'), ('surgery', 'Surgery Billing'), ('other', 'Other'),
                ],
                default='opd', max_length=10,
            ),
        ),
    ]
