# Generated by Django 5.0.14 on 2026-07-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_staff_discount_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bill',
            new_name='billing_bil_status_db3467_idx',
            old_name='billing_bil_status_8a5532_idx',
        ),
        migrations.RenameIndex(
            model_name='bill',
            new_name='billing_bil_payment_3e8ae3_idx',
            old_name='billing_bil_payment_0fe2d4_idx',
        ),
        migrations.RenameIndex(
            model_name='bill',
            new_name='billing_bil_bill_ty_cc44f7_idx',
            old_name='billing_bil_bill_ty_9a1911_idx',
        ),
    ]
