# Generated by Django 5.0.14 on 2026-07-22 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('sputum', 'Sputum'), ('csf', 'CSF'), ('swab', 'Swab'), ('tissue', 'Tissue Biopsy'), ('other', 'Other')], default='blood', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal_range', models.CharField(blank=True, help_text='e.g. "4.0 - 11.0 x10^9/L"', max_length=200)),
                ('report_format', models.CharField(blank=True, default='Standard Report', help_text='e.g. "Standard Report", "CBC Panel", "Culture & Sensitivity"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='departments.department')),
            ],
            options={
                'db_table': 'laboratory_test',
                'ordering': ['name'],
            },
        ),
    ]
