# Generated by Django 5.0.14 on 2026-07-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patienttimeline',
            new_name='workflow_pa_patient_9a83ac_idx',
            old_name='workflow_pa_patient_8b5481_idx',
        ),
        migrations.RenameIndex(
            model_name='patienttimeline',
            new_name='workflow_pa_event_t_a6de8e_idx',
            old_name='workflow_pa_event_t_7b54ca_idx',
        ),
        migrations.RenameIndex(
            model_name='patienttimeline',
            new_name='workflow_pa_source__ce2cd3_idx',
            old_name='workflow_pa_source__729768_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentevent',
            new_name='workflow_pa_bill_id_785d59_idx',
            old_name='workflow_pa_bill_id_984ef1_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentevent',
            new_name='workflow_pa_payment_eae540_idx',
            old_name='workflow_pa_payment_963d9c_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceorder',
            new_name='workflow_se_patient_754c5c_idx',
            old_name='workflow_se_patient_ba05ed_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceorder',
            new_name='workflow_se_service_971570_idx',
            old_name='workflow_se_service_b0d6a2_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceorder',
            new_name='workflow_se_payment_d1f4fd_idx',
            old_name='workflow_se_payment_00d2e6_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceorder',
            new_name='workflow_se_bill_id_8b7ea2_idx',
            old_name='workflow_se_bill_id_8c1f88_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceorder',
            new_name='workflow_se_referra_f01910_idx',
            old_name='workflow_se_referral_3e6d78_idx',
        ),
    ]
