# Generated by Django 5.0.14 on 2026-07-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_rename_referrals_r_referral_dbe7fe_idx_referrals_r_referra_556d28_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='optional_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Optional referral fee/estimated charge, if applicable.', max_digits=10),
        ),
    ]
