# Generated by Django 5.0.14 on 2026-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_radiologyrequest_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='prescription_file',
            field=models.FileField(blank=True, help_text='Upload PDF or Image scan of the handwritten prescription.', null=True, upload_to='consultations/prescriptions/'),
        ),
    ]
