# Generated by hand - no live Django in this sandbox. Run
# `makemigrations --check` after install to confirm this matches.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingnote',
            name='note_type',
            field=models.CharField(
                choices=[
                    ('vitals', 'Vitals Reading'), ('general', 'General Note'),
                    ('progress', 'Progress Note'), ('observation', 'Observation Note'),
                    ('medication', 'Medication Administration'), ('shift_handover', 'Shift Handover'),
                ],
                default='general', max_length=20,
            ),
        ),
    ]
