# Generated by Django 5.0.14 on 2026-07-22 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ot_room',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('surgery_name', models.CharField(max_length=200)),
                ('assistant_surgeons', models.CharField(blank=True, max_length=255)),
                ('anesthesia_type', models.CharField(blank=True, choices=[('general', 'General'), ('regional', 'Regional'), ('local', 'Local'), ('sedation', 'Sedation')], max_length=15)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('scheduled_datetime', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pre_op_notes', models.TextField(blank=True)),
                ('operative_notes', models.TextField(blank=True)),
                ('post_op_notes', models.TextField(blank=True)),
                ('complications', models.TextField(blank=True)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='admissions.admission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries_scheduled', to=settings.AUTH_USER_MODEL)),
                ('ot_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='operation_theatre.otroom')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgeries', to='patients.patient')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgeries_performed', to='doctors.doctor')),
            ],
            options={
                'db_table': 'ot_surgery',
                'ordering': ['-scheduled_datetime'],
            },
        ),
    ]
