# Generated by Django 5.0.14 on 2026-07-22 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('operation_theatre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('default_operating_team', models.CharField(blank=True, help_text='e.g. Surgeon + 2 Assistant Surgeons + Anesthetist + 2 OT Nurses', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_types', to='departments.department')),
            ],
            options={
                'db_table': 'ot_operation_type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='surgery',
            name='operation_type',
            field=models.ForeignKey(blank=True, help_text='Optional link to the priced catalogue entry this surgery is based on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='operation_theatre.operationtype'),
        ),
    ]
