import datetime
import random

from django.contrib.auth.hashers import make_password
from django.core import management
from django.core.files.base import ContentFile
from django.db import transaction
from django.utils import timezone

from django.core.management.base import BaseCommand

NEPALI_FIRST_NAMES_M = [
    'Ramesh', 'Suresh', 'Bikash', 'Anup', 'Prakash', 'Dipesh', 'Sandip', 'Nabin',
    'Kiran', 'Rajesh', 'Bishal', 'Sujan', 'Milan', 'Rohit', 'Ashok', 'Gopal',
    'Hari', 'Narayan', 'Krishna', 'Deepak',
]
NEPALI_FIRST_NAMES_F = [
    'Sunita', 'Sarita', 'Anita', 'Rita', 'Puja', 'Manisha', 'Sabina', 'Kabita',
    'Sushila', 'Radha', 'Gita', 'Laxmi', 'Sarada', 'Nirmala', 'Bimala', 'Sabitri',
    'Rekha', 'Pratima', 'Sangita', 'Anjali',
]
NEPALI_LAST_NAMES = [
    'Sharma', 'Koirala', 'Thapa', 'Gurung', 'Basnet', 'Rai', 'Shrestha', 'Adhikari',
    'Poudel', 'Khadka', 'Magar', 'Tamang', 'Bhattarai', 'Karki', 'Bista', 'Lama',
    'Chhetri', 'Subedi', 'Neupane', 'Regmi',
]

MEDICINES = [
    ('Paracetamol', 'Acetaminophen', '500mg', 'Tablet', 3.5, 5.0),
    ('Amoxicillin', 'Amoxicillin', '500mg', 'Capsule', 6.0, 9.0),
    ('Omeprazole', 'Omeprazole', '20mg', 'Capsule', 4.0, 6.5),
    ('Cetirizine', 'Cetirizine', '10mg', 'Tablet', 2.0, 3.5),
    ('Metformin', 'Metformin', '500mg', 'Tablet', 3.0, 5.0),
    ('Amlodipine', 'Amlodipine', '5mg', 'Tablet', 3.5, 6.0),
    ('Azithromycin', 'Azithromycin', '500mg', 'Tablet', 12.0, 18.0),
    ('Ibuprofen', 'Ibuprofen', '400mg', 'Tablet', 2.5, 4.0),
    ('ORS Powder', 'Oral Rehydration Salts', '', 'Sachet', 8.0, 12.0),
    ('Vitamin C', 'Ascorbic Acid', '500mg', 'Tablet', 2.0, 3.0),
]

LAB_TESTS = ['CBC', 'Blood Sugar (Fasting)', 'Liver Function Test', 'Kidney Function Test',
             'Lipid Profile', 'Urine Routine', 'Widal Test', 'Thyroid Profile']

SURGERY_NAMES = ['Appendectomy', 'Cesarean Section', 'Hernia Repair', 'Cataract Surgery',
                  'Gallbladder Removal', 'Knee Replacement', 'Tonsillectomy']

NEW_ROLE_STAFF = [
    ('ward_admission', 'ward'), ('nursing', 'nurse'), ('operation_theatre', 'ot'),
    ('blood_bank', 'bloodbank'), ('accounts_dept', 'accounts'), ('medical_records', 'medrecords'),
]

DEMO_PDF_BYTES = b'%PDF-1.4\n%Demo placeholder file generated by seed_checkpoint3_data.\n'


class Command(BaseCommand):
    help = (
        'One-shot demo data setup for Checkpoint 3: runs seed_nepal_address and '
        'seed_demo_data if needed, then creates 20+ realistic Nepali records across '
        'every module (patients, staff for the 6 new roles, admissions, surgeries, '
        'blood bank, nursing notes, lab/radiology requests, prescriptions, pharmacy '
        'sales, bills, and patient documents).'
    )

    @transaction.atomic
    def handle(self, *args, **options):
        from patients.models import Patient, Visit, District
        from departments.models import Department
        from doctors.models import Doctor
        from accounts.models import User
        from website.models import HospitalService
        from admissions.models import Ward, Bed, Admission
        from consultations.models import Consultation, PrescriptionItem, LabTestRequest, RadiologyRequest, RequestStatus
        from pharmacy.models import Medicine, PharmacySale, PharmacySaleItem
        from billing.models import Bill, BillItem, PaymentMethod
        from operation_theatre.models import OTRoom, Surgery
        from blood_bank.models import BloodUnit, BloodIssue, BloodGroup
        from nursing.models import NursingNote
        from documents.models import PatientDocument, DocumentCategory

        # --- Prerequisites -------------------------------------------------
        if not District.objects.exists():
            self.stdout.write('Seeding Nepal address data first...')
            management.call_command('seed_nepal_address')
        if not Department.objects.exists():
            self.stdout.write('Seeding base departments/doctors first...')
            management.call_command('seed_demo_data')

        districts = list(District.objects.all())
        departments = list(Department.objects.filter(consultation_fee__gt=0))
        doctors = list(Doctor.objects.all())
        if not districts or not departments or not doctors:
            self.stderr.write(self.style.ERROR(
                'Prerequisite data missing (districts/departments/doctors). '
                'Run seed_nepal_address and seed_demo_data first.'
            ))
            return

        # --- Hospital services (needed for billing) -------------------------
        service_defs = [
            ('SVC-OPD', 'OPD Consultation', 300), ('SVC-ER', 'Emergency Consultation', 800),
            ('SVC-XRAY', 'X-Ray', 600), ('SVC-ECG', 'ECG', 400), ('SVC-BLOOD', 'Blood Test', 350),
            ('SVC-ROOM', 'General Ward Room Charge (per day)', 1500), ('SVC-SURGERY', 'Minor Surgery Fee', 5000),
        ]
        services = []
        for code, name, price in service_defs:
            svc, _ = HospitalService.objects.get_or_create(
                service_code=code, defaults={'name': name, 'price': price},
            )
            services.append(svc)

        # --- Staff accounts for the 6 new roles -----------------------------
        created_staff = 0
        for role, prefix in NEW_ROLE_STAFF:
            for i in range(1, 4):
                username = f'{prefix}{i}'
                if User.objects.filter(username=username).exists():
                    continue
                is_male = i % 2 == 1
                first = random.choice(NEPALI_FIRST_NAMES_M if is_male else NEPALI_FIRST_NAMES_F)
                last = random.choice(NEPALI_LAST_NAMES)
                User.objects.create(
                    username=username, first_name=first, last_name=last,
                    role=role, is_active_staff=True, is_staff=True,
                    password=make_password('sashi'),
                )
                created_staff += 1
        self.stdout.write(self.style.SUCCESS(f'{created_staff} new staff accounts created (password: sashi).'))

        # --- Ward & beds for admissions/nursing -----------------------------
        ward_defs = [('General Ward A', Ward.WardType.GENERAL), ('ICU', Ward.WardType.ICU),
                     ('Maternity Ward', Ward.WardType.MATERNITY), ('Private Ward', Ward.WardType.PRIVATE)]
        wards = []
        for name, wtype in ward_defs:
            ward, _ = Ward.objects.get_or_create(name=name, defaults={'ward_type': wtype})
            wards.append(ward)
            for bed_no in range(1, 6):
                Bed.objects.get_or_create(ward=ward, bed_number=str(bed_no))
        beds = list(Bed.objects.filter(is_occupied=False))

        # --- OT rooms ---------------------------------------------------------
        ot_rooms = []
        for name in ['OT-1', 'OT-2', 'OT-3']:
            room, _ = OTRoom.objects.get_or_create(name=name)
            ot_rooms.append(room)

        # --- Patients (25) ------------------------------------------------
        existing_count = Patient.objects.count()
        target_new_patients = max(0, 25 - existing_count)
        new_patients = []
        for i in range(target_new_patients):
            is_male = i % 2 == 0
            first = random.choice(NEPALI_FIRST_NAMES_M if is_male else NEPALI_FIRST_NAMES_F)
            last = random.choice(NEPALI_LAST_NAMES)
            dob = datetime.date.today() - datetime.timedelta(days=random.randint(365 * 2, 365 * 75))
            patient = Patient.objects.create(
                first_name=first, last_name=last,
                gender=Patient.Gender.MALE if is_male else Patient.Gender.FEMALE,
                date_of_birth=dob,
                phone_number=f"98{random.randint(10000000, 49999999)}",
                district=random.choice(districts),
                municipality='Ward Municipality', ward_number=random.randint(1, 15),
                local_address='Tole Marg',
                blood_group=random.choice([bg for bg, _ in Patient.BloodGroup.choices if bg]),
            )
            new_patients.append(patient)
        patients = list(Patient.objects.all()[:40])
        self.stdout.write(self.style.SUCCESS(f'{len(new_patients)} new patients created ({len(patients)} total available).'))

        # --- Visits + Consultations + Lab/Radiology/Prescriptions ----------
        consultations = []
        for i, patient in enumerate(patients[:25]):
            dept = random.choice(departments)
            doctor = random.choice([d for d in doctors if d.department_id == dept.id] or doctors)
            visit = Visit.objects.create(
                patient=patient, department=dept, doctor=doctor,
                patient_type=Visit.PatientType.NEW if i % 3 == 0 else Visit.PatientType.OLD,
                registration_fee=dept.consultation_fee or 300,
                chief_complaint='Routine checkup / general complaint',
            )
            consultation = Consultation.objects.create(
                visit=visit, doctor=doctor,
                diagnosis=random.choice(['Common Cold', 'Hypertension', 'Gastritis', 'Viral Fever', 'Diabetes Mellitus']),
                clinical_notes='Patient examined; advised medication and follow-up as needed.',
            )
            consultations.append(consultation)

            PrescriptionItem.objects.create(
                consultation=consultation, medicine_name=random.choice(MEDICINES)[0],
                dosage='1 tablet', frequency='Twice daily (BID)', duration='5 days',
                instructions='After meals',
            )

            if i % 2 == 0:
                LabTestRequest.objects.create(
                    consultation=consultation, test_name=random.choice(LAB_TESTS),
                    status=random.choice(list(RequestStatus.values)),
                )
            if i % 3 == 0:
                RadiologyRequest.objects.create(
                    consultation=consultation,
                    service_type=random.choice(['xray', 'ct', 'mri', 'ultrasound']),
                    status=random.choice(list(RequestStatus.values)),
                )

        self.stdout.write(self.style.SUCCESS(
            f'{len(consultations)} visits/consultations created with prescriptions and lab/radiology requests.'
        ))

        # --- Medicines --------------------------------------------------------
        medicines = []
        for i, (name, generic, strength, unit, purchase, selling) in enumerate(MEDICINES, start=1):
            med, _ = Medicine.objects.get_or_create(
                medicine_code=f'MED-{i:04d}',
                defaults={
                    'name': name, 'generic_name': generic, 'strength': strength, 'unit': unit,
                    'purchase_price': purchase, 'selling_price': selling, 'current_stock': 200,
                    'expiry_date': timezone.now().date() + datetime.timedelta(days=365),
                },
            )
            medicines.append(med)

        # --- Admissions (20) + Nursing notes ---------------------------------
        admissions = []
        for i, patient in enumerate(patients[:20]):
            if not beds:
                break
            bed = beds.pop()
            admission = Admission.objects.create(
                patient=patient, department=random.choice(departments),
                admitting_doctor=random.choice(doctors), ward=bed.ward, bed=bed,
                reason_for_admission=random.choice(['Fever for 3 days', 'Post-surgical recovery',
                                                      'Observation', 'Delivery', 'Injury management']),
                diagnosis='Under observation',
            )
            admissions.append(admission)
            for _ in range(2):
                NursingNote.objects.create(
                    admission=admission,
                    note_type=random.choice([NursingNote.NoteType.VITALS, NursingNote.NoteType.GENERAL]),
                    content='Patient stable, resting comfortably.',
                    temperature_c=round(random.uniform(36.5, 38.0), 1),
                    pulse_bpm=random.randint(65, 95),
                    blood_pressure=f"{random.randint(110,130)}/{random.randint(70,90)}",
                    respiratory_rate=random.randint(14, 20),
                    spo2_percent=random.randint(95, 99),
                )
        self.stdout.write(self.style.SUCCESS(f'{len(admissions)} admissions created with nursing notes.'))

        # --- Surgeries (20) -----------------------------------------------
        surgeries = []
        for i, patient in enumerate(patients[:20]):
            surgery = Surgery.objects.create(
                patient=patient, admission=admissions[i] if i < len(admissions) else None,
                surgery_name=random.choice(SURGERY_NAMES), surgeon=random.choice(doctors),
                ot_room=random.choice(ot_rooms), anesthesia_type=random.choice(['general', 'regional', 'local']),
                status=random.choice([Surgery.Status.SCHEDULED, Surgery.Status.COMPLETED]),
                scheduled_datetime=timezone.now() + datetime.timedelta(days=random.randint(-10, 10)),
                charge_amount=random.choice([4000, 8000, 15000, 25000]),
            )
            surgeries.append(surgery)
        self.stdout.write(self.style.SUCCESS(f'{len(surgeries)} surgery records created.'))

        # --- Blood bank (25 units + issues) ---------------------------------
        blood_groups = [bg for bg, _ in BloodGroup.choices]
        units = []
        for i in range(25):
            unit = BloodUnit.objects.create(
                blood_group=random.choice(blood_groups),
                component=random.choice(list(BloodUnit.Component.values)),
                quantity_ml=450,
                donor_name=f"{random.choice(NEPALI_FIRST_NAMES_M)} {random.choice(NEPALI_LAST_NAMES)}",
                donor_phone=f"98{random.randint(10000000, 49999999)}",
                collection_date=timezone.now().date() - datetime.timedelta(days=random.randint(1, 30)),
                expiry_date=timezone.now().date() + datetime.timedelta(days=random.randint(5, 40)),
            )
            units.append(unit)
        for i in range(8):
            unit = units[i]
            BloodIssue.objects.create(
                blood_unit=unit, patient=random.choice(patients),
                purpose='Surgical transfusion', cross_match_notes='Cross-match compatible.',
            )
            BloodUnit.objects.filter(pk=unit.pk).update(status=BloodUnit.Status.ISSUED)
        self.stdout.write(self.style.SUCCESS(f'{len(units)} blood units created, 8 issued.'))

        # --- Bills (25: OPD/IPD/Pharmacy/Surgery) + Pharmacy sales (20) -----
        cashier = User.objects.filter(role='cash_counter').first() or User.objects.filter(is_superuser=True).first()
        bills = []
        for i, patient in enumerate(patients[:25]):
            bill = Bill.objects.create(
                patient=patient, cashier=cashier,
                bill_type=random.choice(['opd', 'ipd', 'lab', 'surgery']),
                payment_method=random.choice([PaymentMethod.CASH, PaymentMethod.ESEWA]),
            )
            svc = random.choice(services)
            BillItem.objects.create(bill=bill, service=svc, service_name=svc.name, unit_price=svc.price, quantity=1)
            bill.recalculate_total()
            bills.append(bill)
        self.stdout.write(self.style.SUCCESS(f'{len(bills)} bills created.'))

        sales = []
        for i, patient in enumerate(patients[:20]):
            sale = PharmacySale.objects.create(
                patient=patient, prescription_source=random.choice(['digital', 'manual', 'walkin']),
                payment_method=random.choice(['cash', 'esewa']), sold_by=cashier,
            )
            med = random.choice(medicines)
            PharmacySaleItem.objects.create(
                sale=sale, medicine=med, medicine_name=med.name, unit_price=med.selling_price,
                quantity=random.randint(1, 3),
            )
            sale.recalculate_total()
            sales.append(sale)
        self.stdout.write(self.style.SUCCESS(f'{len(sales)} pharmacy sales created.'))

        # --- Patient documents (20 placeholder PDFs across categories) -----
        categories = list(DocumentCategory.values)
        docs = []
        for i, patient in enumerate(patients[:20]):
            category = categories[i % len(categories)]
            doc = PatientDocument(
                patient=patient, category=category,
                title=f"{dict(DocumentCategory.choices)[category]} - {patient.full_name}",
                department_note='Seed Data', remarks='Auto-generated demo document.',
            )
            doc.file.save(f"demo_{patient.patient_code}_{i}.pdf", ContentFile(DEMO_PDF_BYTES), save=False)
            doc.save()
            docs.append(doc)
        self.stdout.write(self.style.SUCCESS(f'{len(docs)} patient documents created.'))

        self.stdout.write(self.style.SUCCESS(
            '\nCheckpoint 3 demo data seeding complete. New staff logins use password: sashi '
            '(e.g. username "nurse1", "ot1", "bloodbank1", "accounts1", "medrecords1", "ward1").'
        ))
