from io import BytesIO
from pathlib import Path

from django.conf import settings
from django.http import HttpResponse
from django.utils import timezone
from openpyxl import Workbook
from openpyxl.drawing.image import Image as XLImage
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


def _hospital_meta():
    try:
        from accounts.models import HospitalSetting
        setting = HospitalSetting.get_solo()
        name = setting.name or getattr(settings, 'HOSPITAL_NAME', 'Hamro Hospital')
        address = setting.address or getattr(settings, 'HOSPITAL_ADDRESS', '')
        logo_path = setting.logo.path if setting.logo else None
    except Exception:
        name = getattr(settings, 'HOSPITAL_NAME', 'Hamro Hospital')
        address = getattr(settings, 'HOSPITAL_ADDRESS', 'Kathmandu, Nepal')
        logo_path = None
    if not logo_path:
        static_logo = Path(settings.BASE_DIR) / 'static' / 'images' / 'hospital_logo.png'
        logo_path = str(static_logo) if static_logo.exists() else None
    return name, address, logo_path


def _date_range_label(date_filter='', start_date='', end_date=''):
    labels = {
        'today': 'Today', 'yesterday': 'Yesterday', 'last_7': 'Last 7 Days', '7_days': 'Last 7 Days',
        'last_30': 'Last 30 Days', '30_days': 'Last 30 Days', 'week': 'This Week', 'weekly': 'This Week',
        'month': 'This Month', 'monthly': 'This Month', 'year': 'This Year', 'yearly': 'This Year',
        'all': 'All Time', 'all_time': 'All Time', 'custom': f'Custom Date Range ({start_date or "..."} to {end_date or "..."})',
    }
    return labels.get(date_filter or 'today', date_filter or 'Today')


def export_rows_to_excel(headers, rows, filename, sheet_title='Report', *, title=None, date_filter='', start_date='', end_date='', generated_by='', summary_rows=None):
    """
    Generic professional report export. Keeps backwards compatibility with
    old callers while adding hospital heading, date range, generated-by/date,
    summary totals, and styled table suitable for official records.
    """
    hospital_name, address, logo_path = _hospital_meta()
    wb = Workbook()
    ws = wb.active
    safe_sheet_title = ''.join('-' if ch in '[]:*?/\\' else ch for ch in str(sheet_title or 'Report'))[:31]
    ws.title = safe_sheet_title or 'Report'

    title = title or sheet_title or 'Report'
    date_label = _date_range_label(date_filter, start_date, end_date)
    generated_at = timezone.localtime(timezone.now()).strftime('%Y-%m-%d %H:%M')
    summary_rows = summary_rows or []

    current_row = 1
    if logo_path:
        try:
            img = XLImage(logo_path)
            img.width = 56
            img.height = 56
            ws.add_image(img, 'A1')
        except Exception:
            pass
    ws.merge_cells(start_row=current_row, start_column=2, end_row=current_row, end_column=max(2, len(headers)))
    ws.cell(current_row, 2, hospital_name).font = Font(size=16, bold=True, color='1A365D')
    current_row += 1
    ws.merge_cells(start_row=current_row, start_column=2, end_row=current_row, end_column=max(2, len(headers)))
    ws.cell(current_row, 2, address).font = Font(size=10)
    current_row += 1
    ws.merge_cells(start_row=current_row, start_column=1, end_row=current_row, end_column=max(1, len(headers)))
    ws.cell(current_row, 1, title).font = Font(size=14, bold=True)
    ws.cell(current_row, 1).alignment = Alignment(horizontal='center')
    current_row += 1
    meta = [
        ('Selected Date Range', date_label),
        ('Generated By', generated_by or 'System'),
        ('Generated Date & Time', generated_at),
    ]
    for label, value in meta:
        ws.cell(current_row, 1, label).font = Font(bold=True)
        ws.cell(current_row, 2, value)
        current_row += 1

    if summary_rows:
        current_row += 1
        ws.cell(current_row, 1, 'Summary / Grand Totals').font = Font(bold=True, color='1A365D')
        current_row += 1
        for label, value in summary_rows:
            ws.cell(current_row, 1, label).font = Font(bold=True)
            ws.cell(current_row, 2, value)
            current_row += 1

    current_row += 1
    header_row = current_row
    ws.append(list(headers))
    fill = PatternFill('solid', fgColor='DBEAFE')
    thin = Side(style='thin', color='CBD5E1')
    for cell in ws[header_row]:
        cell.font = Font(bold=True)
        cell.fill = fill
        cell.border = Border(top=thin, left=thin, right=thin, bottom=thin)
        cell.alignment = Alignment(horizontal='center')

    for row in rows:
        ws.append(list(row))
    for worksheet_row in ws.iter_rows(min_row=header_row + 1, max_row=ws.max_row):
        for cell in worksheet_row:
            cell.border = Border(top=thin, left=thin, right=thin, bottom=thin)
            cell.alignment = Alignment(vertical='top')

    ws.freeze_panes = f'A{header_row + 1}'
    ws.auto_filter.ref = f'A{header_row}:{ws.cell(ws.max_row, max(1, len(headers))).coordinate}'
    for col_idx in range(1, max(1, len(headers)) + 1):
        values = [ws.cell(row=row_idx, column=col_idx).value for row_idx in range(1, ws.max_row + 1)]
        length = max((len(str(v)) for v in values if v is not None), default=10)
        ws.column_dimensions[get_column_letter(col_idx)].width = min(max(length + 2, 10), 45)

    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    wb.save(response)
    return response


def export_rows_to_pdf(headers, rows, filename, title='Report', subtitle='', *, date_filter='', start_date='', end_date='', generated_by='', summary_rows=None):
    """Generic report PDF export with hospital heading, metadata, totals, table and page numbers."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image

    hospital_name, address, logo_path = _hospital_meta()
    buffer = BytesIO()
    page_size = landscape(A4) if len(headers) > 5 else A4
    doc = SimpleDocTemplate(buffer, pagesize=page_size, leftMargin=.45*inch, rightMargin=.45*inch, topMargin=.45*inch, bottomMargin=.55*inch)
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='SmallCell', parent=styles['BodyText'], fontSize=7, leading=8.5))
    styles.add(ParagraphStyle(name='Meta', parent=styles['Normal'], fontSize=8, leading=10))

    generated_at = timezone.localtime(timezone.now()).strftime('%Y-%m-%d %H:%M')
    date_label = _date_range_label(date_filter, start_date, end_date)
    summary_rows = summary_rows or []

    heading_cells = []
    if logo_path:
        try:
            heading_cells.append(Image(logo_path, width=.55*inch, height=.55*inch))
        except Exception:
            heading_cells.append('')
    else:
        heading_cells.append('')
    heading_cells.append(Paragraph(f'<b>{hospital_name}</b><br/>{address}<br/><font size="12"><b>{title}</b></font>', styles['Normal']))
    heading = Table([heading_cells], colWidths=[.75*inch, page_size[0] - doc.leftMargin - doc.rightMargin - .75*inch])
    heading.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'MIDDLE')]))
    story = [heading, Spacer(1, 6)]
    if subtitle:
        story.append(Paragraph(subtitle, styles['Meta']))
    story += [
        Paragraph(f'<b>Selected Date Range:</b> {date_label}', styles['Meta']),
        Paragraph(f'<b>Generated By:</b> {generated_by or "System"}', styles['Meta']),
        Paragraph(f'<b>Generated Date & Time:</b> {generated_at}', styles['Meta']),
        Spacer(1, 8),
    ]
    if summary_rows:
        summary_data = [[Paragraph('<b>Summary / Grand Totals</b>', styles['SmallCell']), '']]
        summary_data += [[Paragraph(f'<b>{label}</b>', styles['SmallCell']), Paragraph(str(value), styles['SmallCell'])] for label, value in summary_rows]
        summary_table = Table(summary_data, colWidths=[2.2*inch, 2.2*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#E0F2FE')),
            ('GRID', (0, 0), (-1, -1), .25, colors.lightgrey),
            ('SPAN', (0, 0), (-1, 0)),
        ]))
        story += [summary_table, Spacer(1, 8)]

    def cell(value):
        return Paragraph(str(value if value is not None else ''), styles['SmallCell'])

    data = [[cell(h) for h in headers]] + [[cell(v) for v in row] for row in rows]
    usable_width = page_size[0] - doc.leftMargin - doc.rightMargin
    col_width = usable_width / max(1, len(headers))
    table = Table(data, colWidths=[col_width] * len(headers), repeatRows=1)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#DBEAFE')),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), .25, colors.lightgrey),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')]),
        ('LEFTPADDING', (0, 0), (-1, -1), 3), ('RIGHTPADDING', (0, 0), (-1, -1), 3),
        ('TOPPADDING', (0, 0), (-1, -1), 3), ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ]))
    story.append(table)

    def add_page_number(canvas, _doc):
        canvas.saveState()
        canvas.setFont('Helvetica', 8)
        canvas.drawRightString(page_size[0] - doc.rightMargin, .25*inch, f'Page {canvas.getPageNumber()}')
        canvas.drawString(doc.leftMargin, .25*inch, hospital_name)
        canvas.restoreState()

    doc.build(story, onFirstPage=add_page_number, onLaterPages=add_page_number)
    buffer.seek(0)
    response = HttpResponse(buffer.getvalue(), content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    return response
