# Generated by Django 5.0.14 on 2026-07-22 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('transaction_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('municipality', models.CharField(blank=True, max_length=150)),
                ('ward_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('local_address', models.CharField(blank=True, max_length=200)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('chief_complaint', models.CharField(blank=True, max_length=255)),
                ('patient_type', models.CharField(choices=[('new', 'New Patient'), ('old', 'Old Patient')], default='new', max_length=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('esewa_ref_id', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='appointments/qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='departments.department')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.district')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='doctors.doctor')),
                ('linked_patient', models.ForeignKey(blank=True, help_text='Set by Registration Counter once the patient physically checks in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_appointments', to='patients.patient')),
            ],
            options={
                'db_table': 'appointments_appointment',
                'ordering': ['-created_at'],
            },
        ),
    ]
