# Generated by Django 5.0.14 on 2026-07-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Arrival'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('phonepe', 'PhonePe / FonePay'), ('mobile_banking', 'Mobile Banking'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment')], default='esewa', max_length=15),
        ),
    ]
