# Generated by Django 5.0.14 on 2026-07-22 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('fonepay', 'FonePay'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('insurance', 'Insurance'), ('credit', 'Credit')], max_length=15),
        ),
        migrations.CreateModel(
            name='DiscountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(help_text="e.g. 'Financially weak patient', 'Staff family', 'Charity case'", max_length=150)),
                ('remarks', models.TextField(blank=True, help_text="e.g. 'Patient is financially weak. Operation completed for Rs. 10,000 instead of Rs. 50,000.'")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_approved', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_requests', to='billing.bill')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_discount_request',
                'ordering': ['-requested_at'],
            },
        ),
    ]
