# Generated by Django 5.0.14 on 2026-07-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('icon_class', models.CharField(blank=True, help_text="Bootstrap Icons / Font Awesome class, e.g. 'bi bi-heart-pulse'", max_length=60)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='departments/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments_department',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
