# Generated by Django 5.0.14 on 2026-07-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hamro Hospital', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital/')),
                ('address', models.CharField(default='Maharajgunj, Kathmandu, Nepal', max_length=255)),
                ('phone', models.CharField(default='01-4412345', max_length=50)),
                ('email', models.EmailField(default='contact@tuth.org.np', max_length=254)),
                ('website', models.URLField(default='https://www.tuth.org.np')),
                ('pan_number', models.CharField(blank=True, default='300123456', max_length=50)),
                ('registration_number', models.CharField(blank=True, default='REG-100234', max_length=50)),
                ('opening_hours', models.CharField(default='24/7 for Emergency, OPD: Sun-Fri 8 AM - 2 PM', max_length=255)),
                ('emergency_contact', models.CharField(default='01-4412346', max_length=100)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com')),
                ('footer_information', models.TextField(default='Hamro Hospital Maharajgunj. All rights reserved.')),
                ('default_currency', models.CharField(default='NPR', max_length=10)),
                ('default_timezone', models.CharField(default='Asia/Kathmandu', max_length=50)),
                ('receipt_settings', models.TextField(blank=True, default='Fit on half A4. Print barcode on top-right.')),
                ('print_settings', models.TextField(blank=True, default='Standard A4 Portrait')),
                ('theme_color', models.CharField(default='#1a365d', max_length=20)),
            ],
            options={
                'db_table': 'accounts_hospital_setting',
            },
        ),
    ]
