# Generated by Django 5.0.14 on 2026-07-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_accounts_st_staff__c3a295_idx_accounts_st_staff_i_364d26_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsetting',
            name='paid_leave_days_per_year',
            field=models.PositiveIntegerField(default=5, help_text='Standard paid leave days allowed per staff per year before Super Admin override is required.'),
        ),
        migrations.AddField(
            model_name='staffsalarypayment',
            name='half_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern'), ('temporary', 'Temporary')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalsetting',
            name='paid_leave_days_per_month',
            field=models.PositiveIntegerField(default=5, help_text='Legacy monthly paid leave limit retained for compatibility.'),
        ),
    ]
