# Generated by Django 5.0.14 on 2026-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_hospitalsetting_ehs_additional_charges_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='staff/qrcodes/'),
        ),
    ]
