# Generated by Django 5.0.14 on 2026-07-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_staffsalarypayment_bank_transfer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffleaverequest',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='staff/leave_documents/'),
        ),
    ]
