# Generated by Django 5.0.14 on 2026-07-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_labtestrequest_lab_code_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='recommend_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='recommend_surgery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='recommended_surgery_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
