# Generated by Django 5.0.14 on 2026-07-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultation_recommend_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyrequest',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='radiology/barcodes/'),
        ),
    ]
