# Generated by Django 5.0.14 on 2026-07-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_verification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestrequest',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True when Laboratory staff created this record directly for a walk-in patient.'),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Referring doctor name (walk-in entries)', max_length=150),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Pending'), ('accepted', 'Accepted'), ('sample_collected', 'Sample Collected'), ('in_progress', 'Testing In Progress'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='radiologyrequest',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True when Radiology staff created this record directly for a walk-in patient.'),
        ),
        migrations.AlterField(
            model_name='radiologyrequest',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Referring doctor name (walk-in entries)', max_length=150),
        ),
        migrations.AlterField(
            model_name='radiologyrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Pending'), ('accepted', 'Accepted'), ('sample_collected', 'Sample Collected'), ('in_progress', 'Testing In Progress'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
    ]
