# Generated by Django 5.0.14 on 2026-07-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_referral_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referral',
            new_name='referrals_r_referra_556d28_idx',
            old_name='referrals_r_referral_dbe7fe_idx',
        ),
        migrations.RenameIndex(
            model_name='referral',
            new_name='referrals_r_patient_5883bf_idx',
            old_name='referrals_r_patient__79fc65_idx',
        ),
        migrations.RenameIndex(
            model_name='referral',
            new_name='referrals_r_created_28a752_idx',
            old_name='referrals_r_created_9f76b8_idx',
        ),
    ]
