# Generated by hand - no live Django in this sandbox. Run
# `makemigrations --check` after install to confirm this matches.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_patientdocument_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocument',
            name='category',
            field=models.CharField(
                choices=[
                    ('lab_report', 'Laboratory Report'),
                    ('radiology_report', 'Radiology Report (X-Ray/CT/MRI/USG)'),
                    ('prescription', 'Prescription'), ('doctor_note', "Doctor's Note"),
                    ('nursing_note', 'Nursing Note / Document'),
                    ('discharge_summary', 'Discharge Summary'),
                    ('operation_record', 'Operation / Surgery Record'),
                    ('referral_letter', 'Referral Letter'),
                    ('insurance_document', 'Insurance Document'), ('consent_form', 'Consent Form'),
                    ('invoice', 'Invoice / Billing Document'), ('other', 'Other'),
                ],
                max_length=30,
            ),
        ),
    ]
