# Generated by Django 5.0.14 on 2026-07-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_known_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('esewa', 'eSewa'), ('fonepay', 'FonePay'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Registered - Payment Pending'), ('paid', 'Registered - Payment Completed')], default='pending', max_length=255),
        ),
    ]
