# Generated by Django 5.0.14 on 2026-07-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_visit_payment_method_visit_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='visits/barcodes/'),
        ),
    ]
