# Generated by Django 5.0.14 on 2026-07-22 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ward_type', models.CharField(choices=[('general', 'General'), ('icu', 'ICU'), ('private', 'Private'), ('emergency', 'Emergency'), ('maternity', 'Maternity'), ('pediatric', 'Pediatric')], max_length=15)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'admissions_ward',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='admissions.ward')),
            ],
            options={
                'db_table': 'admissions_bed',
                'ordering': ['ward', 'bed_number'],
                'unique_together': {('ward', 'bed_number')},
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('reason_for_admission', models.CharField(max_length=255)),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('admitted', 'Currently Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred')], default='admitted', max_length=15)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_condition', models.CharField(blank=True, choices=[('recovered', 'Recovered'), ('improved', 'Improved'), ('referred', 'Referred'), ('dama', 'DAMA (Discharge Against Medical Advice)'), ('expired', 'Expired')], max_length=15)),
                ('discharge_summary', models.TextField(blank=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('admitting_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='doctors.doctor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='departments.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patients.patient')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='admissions.bed')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='admissions.ward')),
            ],
            options={
                'db_table': 'admissions_admission',
                'ordering': ['-admission_date'],
            },
        ),
    ]
