# Generated by Django 5.0.14 on 2026-07-22 23:37

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lab_report', 'Laboratory Report'), ('radiology_report', 'Radiology Report (X-Ray/CT/MRI/USG)'), ('prescription', 'Prescription'), ('doctor_note', "Doctor's Note"), ('discharge_summary', 'Discharge Summary'), ('operation_record', 'Operation / Surgery Record'), ('referral_letter', 'Referral Letter'), ('insurance_document', 'Insurance Document'), ('consent_form', 'Consent Form'), ('invoice', 'Invoice / Billing Document'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(help_text='e.g. "CBC Report - 2026-07-20"', max_length=200)),
                ('file', models.FileField(upload_to=documents.models.patient_document_upload_path)),
                ('department_note', models.CharField(blank=True, help_text='Which department/module this came from, e.g. "Laboratory", "Radiology"', max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('uploaded_by_role', models.CharField(blank=True, max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True, help_text='False once a newer version has replaced this file; kept for audit history.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_set', to='documents.patientdocument')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_patient_document',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['patient', 'category'], name='documents_p_patient_b60ef0_idx'), models.Index(fields=['patient', 'is_active'], name='documents_p_patient_0ac3f3_idx')],
            },
        ),
    ]
