# Generated by hand - no live Django in this sandbox (see PASS4_STATUS.md
# and LAB_MODULE_PASS_STATUS.md). Run `makemigrations --check` after install.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_labtestrequest_walkin_fields'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyrequest',
            name='consultation',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='radiology_requests', to='consultations.consultation',
            ),
        ),
        migrations.AlterField(
            model_name='radiologyrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('requested', 'Pending'), ('accepted', 'Accepted'),
                    ('sample_collected', 'Sample Collected'),
                    ('in_progress', 'Testing In Progress'), ('completed', 'Completed'),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='patient',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='manual_radiology_requests', to='patients.patient',
            ),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='referred_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='department_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='clinical_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='referral_letter',
            field=models.FileField(blank=True, null=True, upload_to='radiology/referral_letters/'),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='accepted_by',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='radiology_requests_accepted', to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
