# Generated by Django 5.0.14 on 2026-07-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_medicalservice_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text="Nepali text to scroll (e.g. 'हाम्रो अस्पतालमा तपाईंलाई हार्दिक स्वागत छ।')")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_home_notification',
                'ordering': ['-updated_at'],
            },
        ),
    ]
