# Generated by Django 5.0.14 on 2026-07-29 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_deposit_bedtransfer'),
        ('departments', '0002_departmentunit'),
        ('doctors', '0006_extension_fields_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='activity_recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='diet_advice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='emergency_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='follow_up_additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='follow_up_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_admissions', to='departments.department'),
        ),
        migrations.AddField(
            model_name='admission',
            name='follow_up_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_admissions', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='admission',
            name='medicines_on_discharge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='procedures_performed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='recommended_investigations',
            field=models.TextField(blank=True),
        ),
    ]
