# Generated by Django 5.0.14 on 2026-07-22 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('vitals', 'Vitals Reading'), ('general', 'General Note'), ('medication', 'Medication Administration'), ('shift_handover', 'Shift Handover')], default='general', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse_bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g. 120/80', max_length=20)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('spo2_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('medication_given', models.CharField(blank=True, max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='admissions.admission')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nursing_note',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
