# Generated by Django 5.0.14 on 2026-07-24 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('registration_counter', 'Registration Counter'), ('cash_counter', 'Cash Counter'), ('doctor', 'Doctor'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology Counter'), ('insurance', 'Insurance Counter'), ('ward_admission', 'Ward / Admission'), ('nursing', 'Nursing'), ('operation_theatre', 'Operation Theatre'), ('blood_bank', 'Blood Bank'), ('accounts_dept', 'Accounts'), ('medical_records', 'Medical Records')], help_text='Target role (e.g. all Laboratory staff).', max_length=30, null=True)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Specific user for this notification, or null for all users of a certain role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
