# Generated by Django 5.0.14 on 2026-07-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_extension_counter_label'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffattendance',
            new_name='accounts_st_staff_i_364d26_idx',
            old_name='accounts_st_staff__c3a295_idx',
        ),
        migrations.RenameIndex(
            model_name='staffattendance',
            new_name='accounts_st_date_3b0ec4_idx',
            old_name='accounts_st_date_ae15ab_idx',
        ),
        migrations.RenameIndex(
            model_name='staffleaverequest',
            new_name='accounts_st_staff_i_05e250_idx',
            old_name='accounts_st_staff__9d4087_idx',
        ),
        migrations.RenameIndex(
            model_name='staffleaverequest',
            new_name='accounts_st_start_d_f584d5_idx',
            old_name='accounts_st_start_d_ddfbf8_idx',
        ),
        migrations.RenameIndex(
            model_name='staffsalarypayment',
            new_name='accounts_st_year_e4581d_idx',
            old_name='accounts_st_year_8809c7_idx',
        ),
        migrations.RenameIndex(
            model_name='staffsalarypayment',
            new_name='accounts_st_staff_i_c4a130_idx',
            old_name='accounts_st_staff_i_72e193_idx',
        ),
        migrations.AlterField(
            model_name='hospitalsetting',
            name='email',
            field=models.EmailField(default='info@hamrohospital.example.np', max_length=254),
        ),
        migrations.AlterField(
            model_name='hospitalsetting',
            name='website',
            field=models.URLField(default='https://www.hamrohospital.example.np'),
        ),
    ]
