# Generated by Django 5.0.14 on 2026-07-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_hospitalsetting_paid_leave_days_per_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsetting',
            name='ehs_additional_charges_note',
            field=models.CharField(blank=True, help_text='Optional note for future EHS charges/policies.', max_length=255),
        ),
        migrations.AddField(
            model_name='hospitalsetting',
            name='ehs_followup_ticket_fee',
            field=models.DecimalField(decimal_places=2, default=500, help_text='EHS Service follow-up/old ticket fee configured by Main Super Admin.', max_digits=10),
        ),
        migrations.AddField(
            model_name='hospitalsetting',
            name='ehs_new_ticket_fee',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='EHS Service new ticket fee configured by Main Super Admin.', max_digits=10),
        ),
    ]
