# Generated by Django 5.0.14 on 2026-07-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_staff_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsetting',
            name='admission_base_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Configurable admission fee charged in addition to ward/bed rates if used.', max_digits=10),
        ),
        migrations.AddField(
            model_name='hospitalsetting',
            name='cabin_daily_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Optional standard cabin/private room daily charge reference.', max_digits=10),
        ),
        migrations.AddField(
            model_name='hospitalsetting',
            name='icu_daily_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Optional standard ICU daily charge reference.', max_digits=10),
        ),
    ]
