# Generated by Django 5.0.14 on 2026-07-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_hospitalsetting_admission_base_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalarypayment',
            name='bank_transfer_status',
            field=models.CharField(blank=True, default='', help_text='Future bank integration status/reference.', max_length=30),
        ),
        migrations.AddField(
            model_name='staffsalarypayment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffsalaryprofile',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffsalaryprofile',
            name='salary_type',
            field=models.CharField(choices=[('monthly', 'Monthly Salary'), ('daily', 'Daily Wage')], default='monthly', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('registration_counter', 'Registration Counter'), ('extension_counter', 'EHS Counter'), ('cash_counter', 'Cash Counter'), ('doctor', 'Doctor'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology Counter'), ('insurance', 'Insurance Counter'), ('ward_admission', 'Ward / Admission'), ('nursing', 'Nursing'), ('operation_theatre', 'Operation Theatre'), ('blood_bank', 'Blood Bank'), ('accounts_dept', 'Finance'), ('hospital_staff', 'Hospital Staff'), ('department_head', 'Department Head / Sub-Admin')], help_text='Target role (e.g. all Laboratory staff).', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('registration_counter', 'Registration Counter'), ('extension_counter', 'EHS Counter'), ('cash_counter', 'Cash Counter'), ('doctor', 'Doctor'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology Counter'), ('insurance', 'Insurance Counter'), ('ward_admission', 'Ward / Admission'), ('nursing', 'Nursing'), ('operation_theatre', 'Operation Theatre'), ('blood_bank', 'Blood Bank'), ('accounts_dept', 'Finance'), ('hospital_staff', 'Hospital Staff'), ('department_head', 'Department Head / Sub-Admin')], default='registration_counter', help_text='Primary role used to route the dashboard and gate permissions.', max_length=30),
        ),
    ]
