# Generated by Django 5.0.14 on 2026-07-22 23:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('registration_counter', 'Registration Counter'), ('cash_counter', 'Cash Counter'), ('doctor', 'Doctor'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology Counter'), ('insurance', 'Insurance Counter'), ('ward_admission', 'Ward / Admission'), ('nursing', 'Nursing'), ('operation_theatre', 'Operation Theatre'), ('blood_bank', 'Blood Bank'), ('accounts_dept', 'Accounts'), ('medical_records', 'Medical Records')], default='registration_counter', help_text='Primary role used to route the dashboard and gate permissions.', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active_staff', models.BooleanField(default=True, help_text='Super Admin can deactivate a staff account without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_at_time', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('patient_register', 'Patient Registered'), ('patient_update', 'Patient Updated'), ('visit_correction', 'New Visit (Correction)'), ('appointment_booked', 'Appointment Booked'), ('appointment_paid', 'Appointment Payment Confirmed'), ('payment', 'Payment Collected'), ('reprint', 'Document Reprinted'), ('refund', 'Refund Issued'), ('admission', 'Patient Admitted'), ('discharge', 'Patient Discharged'), ('claim_submitted', 'Insurance Claim Submitted'), ('claim_reviewed', 'Insurance Claim Reviewed'), ('stock_adjusted', 'Medicine Stock Adjusted'), ('pharmacy_sale', 'Pharmacy Sale'), ('lab_result', 'Lab Result Uploaded'), ('radiology_result', 'Radiology Report Uploaded'), ('user_created', 'Staff Account Created'), ('user_deactivated', 'Staff Account Deactivated'), ('document_uploaded', 'Document Uploaded'), ('document_replaced', 'Document Replaced'), ('document_downloaded', 'Document Downloaded'), ('nursing_note', 'Nursing Note Recorded'), ('surgery_scheduled', 'Surgery Scheduled'), ('surgery_updated', 'Surgery Record Updated'), ('blood_unit_added', 'Blood Unit Added to Inventory'), ('blood_issued', 'Blood Unit Issued'), ('refund_requested', 'Refund Requested'), ('refund_reviewed', 'Refund Reviewed'), ('backup_created', 'System Backup Created'), ('restore_performed', 'System Restore Performed'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('patient_id_text', models.CharField(blank=True, help_text='Patient code, if relevant', max_length=50)),
                ('receipt_number', models.CharField(blank=True, help_text='Receipt/bill/claim number, if relevant', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='accounts_au_action_645973_idx'), models.Index(fields=['patient_id_text'], name='accounts_au_patient_202ed6_idx')],
            },
        ),
    ]
