# Generated by hand - no live Django in this sandbox. Run
# `makemigrations --check` after install to confirm this matches.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auditlog_document_deleted_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('login', 'Login'), ('logout', 'Logout'),
                    ('patient_register', 'Patient Registered'), ('patient_update', 'Patient Updated'),
                    ('visit_correction', 'New Visit (Correction)'),
                    ('appointment_booked', 'Appointment Booked'),
                    ('appointment_paid', 'Appointment Payment Confirmed'),
                    ('payment', 'Payment Collected'), ('reprint', 'Document Reprinted'),
                    ('refund', 'Refund Issued'), ('admission', 'Patient Admitted'),
                    ('discharge', 'Patient Discharged'),
                    ('claim_submitted', 'Insurance Claim Submitted'),
                    ('claim_reviewed', 'Insurance Claim Reviewed'),
                    ('stock_adjusted', 'Medicine Stock Adjusted'), ('pharmacy_sale', 'Pharmacy Sale'),
                    ('lab_result', 'Lab Result Uploaded'), ('radiology_result', 'Radiology Report Uploaded'),
                    ('user_created', 'Staff Account Created'), ('user_deactivated', 'Staff Account Deactivated'),
                    ('document_uploaded', 'Document Uploaded'), ('document_replaced', 'Document Replaced'),
                    ('document_downloaded', 'Document Downloaded'), ('document_deleted', 'Document Deleted'),
                    ('nursing_note', 'Nursing Note Recorded'), ('surgery_scheduled', 'Surgery Scheduled'),
                    ('surgery_updated', 'Surgery Record Updated'),
                    ('blood_unit_added', 'Blood Unit Added to Inventory'),
                    ('blood_requested', 'Blood Requested'), ('blood_issued', 'Blood Unit Issued'),
                    ('refund_requested', 'Refund Requested'), ('refund_reviewed', 'Refund Reviewed'),
                    ('backup_created', 'System Backup Created'), ('restore_performed', 'System Restore Performed'),
                    ('other', 'Other'),
                ],
                max_length=30,
            ),
        ),
    ]
