# Generated by hand, following the project convention in 0005 (no live
# Django in this sandbox to run makemigrations - see PASS4_STATUS.md).
# Run `python manage.py makemigrations --check` after install to confirm
# this matches what Django would have generated.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_prescription_file'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestrequest',
            name='consultation',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='lab_requests', to='consultations.consultation',
            ),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('requested', 'Pending'), ('accepted', 'Accepted'),
                    ('sample_collected', 'Sample Collected'),
                    ('in_progress', 'Testing In Progress'), ('completed', 'Completed'),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='patient',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='manual_lab_requests', to='patients.patient',
            ),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='referred_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='department_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='clinical_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='referral_letter',
            field=models.FileField(blank=True, null=True, upload_to='laboratory/referral_letters/'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='accepted_by',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='lab_requests_accepted', to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
