# Generated by Django 5.0.14 on 2026-07-22 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('component', models.CharField(choices=[('whole_blood', 'Whole Blood'), ('packed_cells', 'Packed Red Cells'), ('plasma', 'Fresh Frozen Plasma'), ('platelets', 'Platelets')], default='whole_blood', max_length=20)),
                ('quantity_ml', models.PositiveIntegerField(default=450)),
                ('donor_name', models.CharField(blank=True, max_length=150)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('collection_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('issued', 'Issued'), ('expired', 'Expired'), ('discarded', 'Discarded')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_units_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blood_bank_unit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('cross_match_notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_issues', to='admissions.admission')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_issued', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_issues', to='patients.patient')),
                ('blood_unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='issue', to='blood_bank.bloodunit')),
            ],
            options={
                'db_table': 'blood_bank_issue',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bloodunit',
            index=models.Index(fields=['blood_group', 'status'], name='blood_bank__blood_g_6aea81_idx'),
        ),
    ]
