# Generated by hand - no live Django in this sandbox. Run
# `makemigrations --check` after install to confirm this matches.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
        ('patients', '0001_initial'),
        ('consultations', '0007_radiologyrequest_walkin_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group_needed', models.CharField(choices=[
                    ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'),
                    ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'),
                ], max_length=3)),
                ('component', models.CharField(choices=[
                    ('whole_blood', 'Whole Blood'), ('packed_cells', 'Packed Red Cells'),
                    ('plasma', 'Fresh Frozen Plasma'), ('platelets', 'Platelets'),
                ], default='whole_blood', max_length=20)),
                ('units_needed', models.PositiveIntegerField(default=1)),
                ('urgency', models.CharField(choices=[
                    ('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency'),
                ], default='routine', max_length=10)),
                ('clinical_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[
                    ('pending', 'Pending'), ('issued', 'Issued'), ('cancelled', 'Cancelled'),
                ], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='blood_requests', to='consultations.consultation',
                )),
                ('patient', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='blood_requests', to='patients.patient',
                )),
                ('requested_by', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='blood_requests_made', to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'db_table': 'blood_bank_request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='bloodissue',
            name='issue_report',
            field=models.FileField(blank=True, null=True, upload_to='blood_bank/issue_reports/'),
        ),
        migrations.AddField(
            model_name='bloodissue',
            name='blood_request',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='issue', to='blood_bank.bloodrequest',
            ),
        ),
    ]
