# Generated by Django 5.0.14 on 2026-07-22 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_at_registration',
            field=models.CharField(blank=True, help_text="How the age was entered at registration, e.g. '24 Years', '11 Years 2 Months', '15 Days'. Date of Birth above is auto-calculated from this and can be corrected manually.", max_length=50),
        ),
        migrations.CreateModel(
            name='InsuranceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Gold', 'Silver', 'Government Employee'", max_length=100)),
                ('coverage_percent', models.DecimalField(decimal_places=2, help_text='Percentage of the bill covered by insurance, e.g. 80.00', max_digits=5)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='patients.insurancecompany')),
            ],
            options={
                'db_table': 'insurance_category',
                'ordering': ['company__name', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_category',
            field=models.ForeignKey(blank=True, help_text='Coverage tier used to auto-calculate insurance billing splits.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.insurancecategory'),
        ),
    ]
