"""
seed_final_requirements: brings every module up to the volume required by
the "Final Requirements" spec (100+ patients, 500+ medicines, 100+ lab
tests, 100+ radiology tests, 100+ billing items, 100+ operations, insurance
categories, extra beds, testimonials, gallery images) using realistic
Nepali names written in English transliteration throughout (e.g. "Ram
Bahadur", "Sita Devi", "Gopal Sharma") - never Devanagari script.

Safe to re-run: everything uses get_or_create/update_or_create keyed on a
unique code/name, so running it twice just tops up counts rather than
duplicating data.
"""
import datetime
import random

from django.core import management
from django.core.files.base import ContentFile
from django.db import transaction
from django.utils import timezone
from django.utils.text import slugify

from django.core.management.base import BaseCommand

# ---------------------------------------------------------------------------
# Name pools (English transliteration of common Nepali names - spec requires
# this over Devanagari script).
# ---------------------------------------------------------------------------
FIRST_NAMES_M = [
    'Ram', 'Shyam', 'Hari', 'Gopal', 'Krishna', 'Bishnu', 'Ganesh', 'Mahesh',
    'Suresh', 'Ramesh', 'Dinesh', 'Mahendra', 'Narendra', 'Surendra', 'Rajendra',
    'Bikash', 'Anup', 'Prakash', 'Dipesh', 'Sandip', 'Nabin', 'Kiran', 'Rajesh',
    'Bishal', 'Sujan', 'Milan', 'Rohit', 'Ashok', 'Deepak', 'Narayan', 'Bimal',
    'Ram Bahadur', 'Tek Bahadur', 'Man Bahadur', 'Him Bahadur', 'Jit Bahadur',
    'Buddha', 'Santosh', 'Sanjay', 'Sunil', 'Manoj', 'Binod', 'Bharat',
    'Yagya', 'Keshav', 'Madhav', 'Basudev', 'Damodar', 'Umesh', 'Yubraj', 'Padam',
]
FIRST_NAMES_F = [
    'Sita', 'Gita', 'Radha', 'Laxmi', 'Kamala', 'Bimala', 'Nirmala', 'Sarada',
    'Sunita', 'Sarita', 'Anita', 'Rita', 'Puja', 'Manisha', 'Sabina', 'Kabita',
    'Sushila', 'Sabitri', 'Rekha', 'Pratima', 'Sangita', 'Anjali', 'Devi',
    'Sita Devi', 'Kamala Devi', 'Laxmi Devi', 'Radha Devi', 'Parbati',
    'Durga', 'Saraswati', 'Ganga', 'Kalpana', 'Sarala', 'Renuka', 'Meera',
    'Indira', 'Shova', 'Shanti', 'Kamana', 'Bina', 'Bandana', 'Roshani',
    'Sarmila', 'Bishnu Maya', 'Him Kumari', 'Man Kumari', 'Til Kumari', 'Goma',
]
LAST_NAMES = [
    'Sharma', 'Koirala', 'Thapa', 'Gurung', 'Basnet', 'Rai', 'Shrestha', 'Adhikari',
    'Poudel', 'Khadka', 'Magar', 'Tamang', 'Bhattarai', 'Karki', 'Bista', 'Lama',
    'Chhetri', 'Subedi', 'Neupane', 'Regmi', 'Acharya', 'Dahal', 'Bhandari',
    'Pandey', 'Joshi', 'Baral', 'Ojha', 'Devkota', 'Khatri', 'Rana', 'Malla',
    'Yadav', 'Mahato', 'Sah', 'Limbu', 'Rijal', 'Paudel', 'Ghimire', 'Bogati',
]

DEMO_PDF_BYTES = b'%PDF-1.4\n%Demo placeholder file generated by seed_final_requirements.\n'


# ---------------------------------------------------------------------------
# Medicines: ~55 generic drugs x several strength/brand/manufacturer variants
# = 500+ unique catalogue rows.
# ---------------------------------------------------------------------------
GENERIC_DRUGS = [
    ('Paracetamol', 'Analgesic/Antipyretic', ['125mg', '250mg', '500mg', '650mg'], 'Tablet'),
    ('Ibuprofen', 'NSAID', ['200mg', '400mg', '600mg'], 'Tablet'),
    ('Diclofenac', 'NSAID', ['25mg', '50mg', '75mg'], 'Tablet'),
    ('Aspirin', 'Antiplatelet', ['75mg', '150mg', '300mg'], 'Tablet'),
    ('Amoxicillin', 'Antibiotic', ['250mg', '500mg'], 'Capsule'),
    ('Azithromycin', 'Antibiotic', ['250mg', '500mg'], 'Tablet'),
    ('Ciprofloxacin', 'Antibiotic', ['250mg', '500mg'], 'Tablet'),
    ('Amoxicillin + Clavulanate', 'Antibiotic', ['625mg', '1g'], 'Tablet'),
    ('Cephalexin', 'Antibiotic', ['250mg', '500mg'], 'Capsule'),
    ('Metronidazole', 'Antibiotic', ['200mg', '400mg'], 'Tablet'),
    ('Doxycycline', 'Antibiotic', ['100mg'], 'Capsule'),
    ('Omeprazole', 'PPI', ['20mg', '40mg'], 'Capsule'),
    ('Pantoprazole', 'PPI', ['20mg', '40mg'], 'Tablet'),
    ('Ranitidine', 'Antacid', ['150mg', '300mg'], 'Tablet'),
    ('Domperidone', 'Antiemetic', ['10mg'], 'Tablet'),
    ('Ondansetron', 'Antiemetic', ['4mg', '8mg'], 'Tablet'),
    ('Cetirizine', 'Antihistamine', ['5mg', '10mg'], 'Tablet'),
    ('Loratadine', 'Antihistamine', ['10mg'], 'Tablet'),
    ('Chlorpheniramine', 'Antihistamine', ['4mg'], 'Tablet'),
    ('Metformin', 'Antidiabetic', ['500mg', '850mg', '1000mg'], 'Tablet'),
    ('Glimepiride', 'Antidiabetic', ['1mg', '2mg', '4mg'], 'Tablet'),
    ('Insulin Regular', 'Antidiabetic', ['40IU/ml', '100IU/ml'], 'Injection'),
    ('Amlodipine', 'Antihypertensive', ['2.5mg', '5mg', '10mg'], 'Tablet'),
    ('Losartan', 'Antihypertensive', ['25mg', '50mg', '100mg'], 'Tablet'),
    ('Atenolol', 'Antihypertensive', ['25mg', '50mg'], 'Tablet'),
    ('Enalapril', 'Antihypertensive', ['5mg', '10mg'], 'Tablet'),
    ('Hydrochlorothiazide', 'Diuretic', ['12.5mg', '25mg'], 'Tablet'),
    ('Furosemide', 'Diuretic', ['20mg', '40mg'], 'Tablet'),
    ('Atorvastatin', 'Statin', ['10mg', '20mg', '40mg'], 'Tablet'),
    ('Rosuvastatin', 'Statin', ['5mg', '10mg', '20mg'], 'Tablet'),
    ('Salbutamol', 'Bronchodilator', ['2mg', '4mg'], 'Tablet'),
    ('Salbutamol Inhaler', 'Bronchodilator', ['100mcg'], 'Inhaler'),
    ('Montelukast', 'Anti-asthmatic', ['4mg', '5mg', '10mg'], 'Tablet'),
    ('Prednisolone', 'Corticosteroid', ['5mg', '10mg', '20mg'], 'Tablet'),
    ('Dexamethasone', 'Corticosteroid', ['0.5mg', '4mg'], 'Tablet'),
    ('Hydrocortisone Cream', 'Corticosteroid', ['1%'], 'Cream'),
    ('Betamethasone Cream', 'Corticosteroid', ['0.1%'], 'Cream'),
    ('Clotrimazole Cream', 'Antifungal', ['1%'], 'Cream'),
    ('Fluconazole', 'Antifungal', ['150mg'], 'Capsule'),
    ('Albendazole', 'Antihelminthic', ['200mg', '400mg'], 'Tablet'),
    ('Vitamin C', 'Vitamin', ['250mg', '500mg'], 'Tablet'),
    ('Vitamin B Complex', 'Vitamin', ['Standard'], 'Tablet'),
    ('Folic Acid', 'Vitamin', ['5mg'], 'Tablet'),
    ('Iron + Folic Acid', 'Hematinic', ['Standard'], 'Tablet'),
    ('Calcium + Vitamin D3', 'Supplement', ['500mg'], 'Tablet'),
    ('Multivitamin Syrup', 'Vitamin', ['Standard'], 'Syrup'),
    ('ORS Powder', 'Rehydration', ['21g Sachet'], 'Sachet'),
    ('Zinc Sulphate Syrup', 'Supplement', ['20mg/5ml'], 'Syrup'),
    ('Tramadol', 'Analgesic', ['50mg', '100mg'], 'Capsule'),
    ('Diazepam', 'Anxiolytic', ['2mg', '5mg'], 'Tablet'),
    ('Amitriptyline', 'Antidepressant', ['10mg', '25mg'], 'Tablet'),
    ('Sertraline', 'Antidepressant', ['50mg', '100mg'], 'Tablet'),
    ('Levothyroxine', 'Thyroid Hormone', ['25mcg', '50mcg', '100mcg'], 'Tablet'),
    ('Carbimazole', 'Antithyroid', ['5mg', '10mg'], 'Tablet'),
    ('Warfarin', 'Anticoagulant', ['1mg', '5mg'], 'Tablet'),
    ('Clopidogrel', 'Antiplatelet', ['75mg'], 'Tablet'),
    ('Normal Saline IV', 'IV Fluid', ['500ml', '1000ml'], 'IV Fluid'),
    ('Dextrose 5% IV', 'IV Fluid', ['500ml'], 'IV Fluid'),
    ('Ringer Lactate IV', 'IV Fluid', ['500ml'], 'IV Fluid'),
    ('Povidone Iodine Solution', 'Antiseptic', ['10%'], 'Solution'),
    ('Chlorhexidine Solution', 'Antiseptic', ['4%'], 'Solution'),
]
MANUFACTURERS = [
    'Deurali-Janta Pharmaceuticals', 'Nepal Pharmaceuticals Laboratories', 'Asian Pharmaceuticals',
    'National Healthcare', 'Time Pharmaceuticals', 'Total Pharma', 'Ohm Pharma', 'Sunrise Pharmaceuticals',
    'Quest Pharmaceuticals', 'Lomus Pharmaceuticals', 'Diamond Pharmaceuticals', 'Modern Drugs',
]
BRAND_PREFIXES = ['Cure', 'Nova', 'Well', 'Life', 'Med', 'Bio', 'Health', 'Care', 'Prime', 'Rex']


# ---------------------------------------------------------------------------
# Laboratory tests (100+), grouped for realistic sample_type/price ranges.
# ---------------------------------------------------------------------------
LAB_TESTS = [
    ('Complete Blood Count (CBC)', 'blood', 'Standard Report', 400),
    ('Erythrocyte Sedimentation Rate (ESR)', 'blood', 'Standard Report', 250),
    ('Peripheral Blood Smear', 'blood', 'Standard Report', 300),
    ('Reticulocyte Count', 'blood', 'Standard Report', 350),
    ('Blood Group & Rh Typing', 'blood', 'Standard Report', 300),
    ('Coombs Test (Direct)', 'blood', 'Standard Report', 500),
    ('Blood Sugar Fasting (FBS)', 'blood', 'Standard Report', 200),
    ('Blood Sugar Post Prandial (PPBS)', 'blood', 'Standard Report', 200),
    ('Random Blood Sugar (RBS)', 'blood', 'Standard Report', 180),
    ('HbA1c (Glycated Hemoglobin)', 'blood', 'Standard Report', 900),
    ('Lipid Profile', 'blood', 'Panel Report', 900),
    ('Liver Function Test (LFT)', 'blood', 'Panel Report', 900),
    ('Kidney Function Test (KFT/RFT)', 'blood', 'Panel Report', 900),
    ('Serum Electrolytes (Na/K/Cl)', 'blood', 'Standard Report', 700),
    ('Serum Calcium', 'blood', 'Standard Report', 350),
    ('Serum Phosphorus', 'blood', 'Standard Report', 350),
    ('Serum Uric Acid', 'blood', 'Standard Report', 350),
    ('Serum Creatinine', 'blood', 'Standard Report', 300),
    ('Blood Urea Nitrogen (BUN)', 'blood', 'Standard Report', 300),
    ('Thyroid Profile (T3/T4/TSH)', 'blood', 'Panel Report', 1200),
    ('TSH Only', 'blood', 'Standard Report', 600),
    ('Free T3', 'blood', 'Standard Report', 600),
    ('Free T4', 'blood', 'Standard Report', 600),
    ('Vitamin D (25-OH)', 'blood', 'Standard Report', 2500),
    ('Vitamin B12', 'blood', 'Standard Report', 1800),
    ('Serum Iron Studies', 'blood', 'Panel Report', 1500),
    ('Serum Ferritin', 'blood', 'Standard Report', 1200),
    ('C-Reactive Protein (CRP)', 'blood', 'Standard Report', 700),
    ('Rheumatoid Factor (RA Test)', 'blood', 'Standard Report', 700),
    ('ASO Titre', 'blood', 'Standard Report', 700),
    ('Widal Test', 'blood', 'Standard Report', 350),
    ('Weil-Felix Test', 'blood', 'Standard Report', 400),
    ('VDRL/RPR Test', 'blood', 'Standard Report', 350),
    ('TPHA Test', 'blood', 'Standard Report', 500),
    ('HIV I & II ELISA', 'blood', 'Standard Report', 600),
    ('HBsAg (Hepatitis B)', 'blood', 'Standard Report', 500),
    ('Anti-HCV (Hepatitis C)', 'blood', 'Standard Report', 700),
    ('Hepatitis A IgM', 'blood', 'Standard Report', 900),
    ('Hepatitis E IgM', 'blood', 'Standard Report', 900),
    ('Dengue NS1 Antigen', 'blood', 'Standard Report', 900),
    ('Dengue IgM/IgG', 'blood', 'Standard Report', 900),
    ('Malaria Antigen (RDT)', 'blood', 'Standard Report', 400),
    ('Typhidot (Typhoid IgM/IgG)', 'blood', 'Standard Report', 800),
    ('Chikungunya IgM', 'blood', 'Standard Report', 1000),
    ('Japanese Encephalitis IgM', 'blood', 'Standard Report', 1200),
    ('COVID-19 RT-PCR', 'swab', 'Standard Report', 2000),
    ('COVID-19 Rapid Antigen', 'swab', 'Standard Report', 600),
    ('Amylase', 'blood', 'Standard Report', 500),
    ('Lipase', 'blood', 'Standard Report', 600),
    ('Troponin I', 'blood', 'Standard Report', 1500),
    ('CPK (Creatine Phosphokinase)', 'blood', 'Standard Report', 700),
    ('CPK-MB', 'blood', 'Standard Report', 900),
    ('D-Dimer', 'blood', 'Standard Report', 1800),
    ('Prothrombin Time (PT/INR)', 'blood', 'Standard Report', 600),
    ('APTT (Clotting Profile)', 'blood', 'Standard Report', 700),
    ('Bleeding Time & Clotting Time', 'blood', 'Standard Report', 300),
    ('Beta hCG (Pregnancy, Quantitative)', 'blood', 'Standard Report', 900),
    ('Urine Pregnancy Test', 'urine', 'Standard Report', 200),
    ('FSH', 'blood', 'Standard Report', 900),
    ('LH', 'blood', 'Standard Report', 900),
    ('Prolactin', 'blood', 'Standard Report', 1000),
    ('Testosterone', 'blood', 'Standard Report', 1200),
    ('Estrogen (Estradiol)', 'blood', 'Standard Report', 1200),
    ('PSA (Prostate Specific Antigen)', 'blood', 'Standard Report', 1500),
    ('CA-125 (Ovarian Marker)', 'blood', 'Standard Report', 2000),
    ('CEA (Tumor Marker)', 'blood', 'Standard Report', 1800),
    ('AFP (Alpha-Fetoprotein)', 'blood', 'Standard Report', 1800),
    ('Serum Cortisol', 'blood', 'Standard Report', 1500),
    ('ACTH', 'blood', 'Standard Report', 2000),
    ('Growth Hormone', 'blood', 'Standard Report', 2200),
    ('Parathyroid Hormone (PTH)', 'blood', 'Standard Report', 2200),
    ('Insulin Level', 'blood', 'Standard Report', 1800),
    ('C-Peptide', 'blood', 'Standard Report', 1800),
    ('Serum Magnesium', 'blood', 'Standard Report', 500),
    ('Serum Ammonia', 'blood', 'Standard Report', 900),
    ('Serum Lactate', 'blood', 'Standard Report', 900),
    ('Arterial Blood Gas (ABG)', 'blood', 'Standard Report', 1200),
    ('H. Pylori Antibody', 'blood', 'Standard Report', 900),
    ('H. Pylori Stool Antigen', 'stool', 'Standard Report', 1000),
    ('Urine Routine Examination', 'urine', 'Standard Report', 200),
    ('Urine Microalbumin', 'urine', 'Standard Report', 700),
    ('24-Hour Urine Protein', 'urine', 'Standard Report', 800),
    ('Urine Culture & Sensitivity', 'urine', 'Culture Report', 900),
    ('Creatinine Clearance', 'urine', 'Standard Report', 900),
    ('Stool Routine Examination', 'stool', 'Standard Report', 200),
    ('Stool Occult Blood', 'stool', 'Standard Report', 350),
    ('Stool for Ova & Parasite', 'stool', 'Standard Report', 300),
    ('Stool Culture & Sensitivity', 'stool', 'Culture Report', 900),
    ('Sputum for AFB (Smear)', 'sputum', 'Standard Report', 300),
    ('Sputum Culture & Sensitivity', 'sputum', 'Culture Report', 900),
    ('Throat Swab Culture', 'swab', 'Culture Report', 800),
    ('Wound Swab Culture', 'swab', 'Culture Report', 900),
    ('Blood Culture & Sensitivity', 'blood', 'Culture Report', 1500),
    ('Semen Analysis', 'other', 'Standard Report', 900),
    ('Pap Smear', 'swab', 'Cytology Report', 1000),
    ('CSF Analysis', 'csf', 'Standard Report', 1500),
    ('Pleural Fluid Analysis', 'other', 'Standard Report', 1500),
    ('Ascitic Fluid Analysis', 'other', 'Standard Report', 1500),
    ('Synovial Fluid Analysis', 'other', 'Standard Report', 1500),
    ('Bone Marrow Aspiration Cytology', 'tissue', 'Cytology Report', 3000),
    ('Biopsy Histopathology', 'tissue', 'Histopathology Report', 2500),
    ('FNAC (Fine Needle Aspiration Cytology)', 'tissue', 'Cytology Report', 1500),
    ('Vitamin B1 (Thiamine)', 'blood', 'Standard Report', 1500),
    ('Vitamin B6', 'blood', 'Standard Report', 1500),
    ('Folate Level', 'blood', 'Standard Report', 1500),
    ('Serum Zinc Level', 'blood', 'Standard Report', 1800),
    ('Serum Copper Level', 'blood', 'Standard Report', 1800),
    ('Serum Lead Level', 'blood', 'Standard Report', 2200),
    ('Blood Alcohol Level', 'blood', 'Standard Report', 1200),
    ('Urine Drug Screen Panel', 'urine', 'Panel Report', 2000),
    ('Ketone Bodies (Urine)', 'urine', 'Standard Report', 250),
    ('Glucose Tolerance Test (GTT)', 'blood', 'Panel Report', 900),
]

# ---------------------------------------------------------------------------
# Radiology tests (100+).
# ---------------------------------------------------------------------------
XRAY_PARTS = [
    'Chest PA View', 'Chest Lateral View', 'Abdomen Erect View', 'Abdomen Supine View',
    'Skull AP View', 'Skull Lateral View', "Skull Towne's View", 'Cervical Spine AP/Lateral',
    'Thoracic Spine AP/Lateral', 'Lumbar Spine AP/Lateral', 'Lumbosacral Spine', 'KUB Region',
    'Pelvis AP View', 'Both Hip Joints', 'Right Hand', 'Left Hand', 'Right Wrist', 'Left Wrist',
    'Right Elbow', 'Left Elbow', 'Right Shoulder', 'Left Shoulder', 'Right Knee', 'Left Knee',
    'Both Knees (Standing)', 'Right Ankle', 'Left Ankle', 'Right Foot', 'Left Foot',
    'Both Femur', 'Both Tibia-Fibula', 'Paranasal Sinuses (PNS) View', 'Mastoid View',
    'Orthopantomogram (OPG - Dental)', 'Soft Tissue Neck', 'Both Clavicle',
]
CONTRAST_STUDIES = [
    'Barium Swallow', 'Barium Meal', 'Barium Meal Follow Through', 'Barium Enema',
    'Intravenous Pyelogram (IVP/IVU)', 'Micturating Cystourethrogram (MCU)',
    'Hysterosalpingography (HSG)', 'Sialography', 'Fistulogram', 'Sinogram',
]
ULTRASOUND_TESTS = [
    'USG Whole Abdomen', 'USG Upper Abdomen', 'USG Pelvis', 'USG KUB Region',
    'USG Obstetric (Pregnancy)', 'USG Thyroid', 'USG Both Breasts', 'USG Scrotal',
    'USG Neck Soft Tissue', 'USG Small Parts', 'Doppler Study - Carotid',
    'Doppler Study - Renal', 'Doppler Study - Lower Limb Venous', 'Doppler Study - Upper Limb Venous',
    'Doppler Study - Testicular', 'USG Transvaginal (TVS)', 'USG Hip (Infant Screening)',
    'USG Chest / Pleural',
]
CT_TESTS = [
    'CT Head Plain', 'CT Head with Contrast', 'CT Chest Plain', 'HRCT Chest',
    'CT Abdomen Plain', 'CT Abdomen with Contrast', 'CT Whole Abdomen', 'CT KUB',
    'CT Cervical Spine', 'CT Thoracic Spine', 'CT Lumbar Spine', 'CT PNS (Sinuses)',
    'CT Temporal Bone', 'CT Angiography - Brain', 'CT Angiography - Chest',
    'CT Angiography - Abdomen', 'CT Angiography - Peripheral Vessels', 'CT Extremity',
]
MRI_TESTS = [
    'MRI Brain Plain', 'MRI Brain with Contrast', 'MRI Cervical Spine', 'MRI Thoracic Spine',
    'MRI Lumbar Spine', 'MRI Whole Spine', 'MRI Right Knee', 'MRI Left Knee',
    'MRI Right Shoulder', 'MRI Left Shoulder', 'MRI Whole Abdomen', 'MRI Pelvis',
    'MRI Both Breasts', 'MR Angiography - Brain (MRA)', 'MR Venography - Brain (MRV)',
]
OTHER_RADIOLOGY = [
    'Mammography Bilateral', 'Mammography Unilateral', 'DEXA Scan (Bone Density)',
    'Fluoroscopy Guided Procedure', 'Echocardiography (2D Echo)', 'Stress Echocardiography',
    'Trans-Esophageal Echocardiography (TEE)', 'ECG (Resting)', 'ECG (Exercise / TMT)',
]

# ---------------------------------------------------------------------------
# Operation types (100+), grouped by surgical department per spec section 5.
# ---------------------------------------------------------------------------
OPERATIONS = {
    'Cardiology': [
        ('Coronary Artery Bypass Graft (CABG)', 180000, 'Cardiac Surgeon + 2 Assistants + Perfusionist + Anesthetist'),
        ('Mitral Valve Replacement', 200000, 'Cardiac Surgeon + 2 Assistants + Perfusionist + Anesthetist'),
        ('Aortic Valve Replacement', 210000, 'Cardiac Surgeon + 2 Assistants + Perfusionist + Anesthetist'),
        ('ASD Closure', 120000, 'Cardiac Surgeon + Assistant + Anesthetist'),
        ('VSD Closure', 130000, 'Cardiac Surgeon + Assistant + Anesthetist'),
        ('Permanent Pacemaker Implantation', 90000, 'Cardiologist + Assistant + Nurse'),
        ('Angioplasty with Stent', 150000, 'Interventional Cardiologist + Assistant + Nurse'),
        ('Pericardiectomy', 100000, 'Cardiac Surgeon + Assistant + Anesthetist'),
        ('Permanent Pacemaker Battery Change', 40000, 'Cardiologist + Nurse'),
    ],
    'Neurology': [
        ('Craniotomy for Brain Tumor', 220000, 'Neurosurgeon + 2 Assistants + Anesthetist + 2 OT Nurses'),
        ('Craniotomy for Hematoma Evacuation', 180000, 'Neurosurgeon + Assistant + Anesthetist'),
        ('Ventriculoperitoneal (VP) Shunt', 90000, 'Neurosurgeon + Assistant + Anesthetist'),
        ('Burr Hole Surgery', 60000, 'Neurosurgeon + Assistant + Anesthetist'),
        ('Cerebral Aneurysm Clipping', 250000, 'Neurosurgeon + 2 Assistants + Anesthetist'),
        ('Lumbar Discectomy', 110000, 'Neurosurgeon + Assistant + Anesthetist'),
        ('Spinal Laminectomy', 120000, 'Neurosurgeon + Assistant + Anesthetist'),
        ('Peripheral Nerve Repair', 70000, 'Neurosurgeon + Assistant'),
        ('Carpal Tunnel Release', 35000, 'Surgeon + Assistant'),
        ('Spinal Cord Tumor Excision', 230000, 'Neurosurgeon + 2 Assistants + Anesthetist'),
    ],
    'ENT': [
        ('Tonsillectomy', 35000, 'ENT Surgeon + Assistant + Anesthetist'),
        ('Adenoidectomy', 30000, 'ENT Surgeon + Assistant + Anesthetist'),
        ('Septoplasty', 45000, 'ENT Surgeon + Assistant + Anesthetist'),
        ('Mastoidectomy', 60000, 'ENT Surgeon + Assistant + Anesthetist'),
        ('Myringotomy with Grommet', 25000, 'ENT Surgeon + Assistant'),
        ('Functional Endoscopic Sinus Surgery (FESS)', 70000, 'ENT Surgeon + Assistant + Anesthetist'),
        ('Thyroidectomy', 80000, 'ENT/General Surgeon + Assistant + Anesthetist'),
        ('Cochlear Implant Surgery', 400000, 'ENT Surgeon + 2 Assistants + Audiologist + Anesthetist'),
        ('Laryngectomy', 150000, 'ENT Surgeon + 2 Assistants + Anesthetist'),
    ],
    'Ophthalmology': [
        ('Cataract Surgery (Phaco with IOL)', 40000, 'Ophthalmic Surgeon + Assistant'),
        ('Cataract Surgery (SICS)', 25000, 'Ophthalmic Surgeon + Assistant'),
        ('Pterygium Excision', 20000, 'Ophthalmic Surgeon + Assistant'),
        ('Glaucoma Surgery (Trabeculectomy)', 45000, 'Ophthalmic Surgeon + Assistant'),
        ('Retinal Detachment Surgery', 90000, 'Ophthalmic Surgeon + Assistant + Anesthetist'),
        ('Squint Correction Surgery', 35000, 'Ophthalmic Surgeon + Assistant'),
        ('Corneal Transplant', 100000, 'Ophthalmic Surgeon + Assistant + Anesthetist'),
        ('Ptosis Correction Surgery', 30000, 'Ophthalmic Surgeon + Assistant'),
        ('Dacryocystorhinostomy (DCR)', 35000, 'Ophthalmic Surgeon + Assistant'),
    ],
    'Orthopedics': [
        ('Total Knee Replacement', 250000, 'Orthopedic Surgeon + 2 Assistants + Anesthetist'),
        ('Total Hip Replacement', 280000, 'Orthopedic Surgeon + 2 Assistants + Anesthetist'),
        ('Hip Fracture Fixation', 120000, 'Orthopedic Surgeon + Assistant + Anesthetist'),
        ('Femur Fracture Fixation (ORIF)', 100000, 'Orthopedic Surgeon + Assistant + Anesthetist'),
        ('Tibia Fracture Fixation', 90000, 'Orthopedic Surgeon + Assistant + Anesthetist'),
        ('Spine Fixation Surgery', 220000, 'Orthopedic Surgeon + 2 Assistants + Anesthetist'),
        ('Arthroscopy - Knee', 80000, 'Orthopedic Surgeon + Assistant + Anesthetist'),
        ('ACL Reconstruction', 130000, 'Orthopedic Surgeon + Assistant + Anesthetist'),
        ('Clubfoot Correction Surgery', 60000, 'Orthopedic Surgeon + Assistant + Anesthetist'),
        ('Shoulder Replacement', 260000, 'Orthopedic Surgeon + 2 Assistants + Anesthetist'),
    ],
    'Dermatology': [
        ('Burn Contracture Release', 90000, 'Plastic Surgeon + Assistant + Anesthetist'),
        ('Skin Grafting', 70000, 'Plastic Surgeon + Assistant + Anesthetist'),
        ('Cleft Lip Repair', 80000, 'Plastic Surgeon + Assistant + Anesthetist'),
        ('Cleft Palate Repair', 100000, 'Plastic Surgeon + Assistant + Anesthetist'),
        ('Rhinoplasty', 90000, 'Plastic Surgeon + Assistant + Anesthetist'),
        ('Scar Revision Surgery', 40000, 'Plastic Surgeon + Assistant'),
        ('Liposuction', 80000, 'Plastic Surgeon + Assistant + Anesthetist'),
        ('Abdominoplasty', 120000, 'Plastic Surgeon + Assistant + Anesthetist'),
    ],
    'Urology': [
        ('TURP (Prostate Resection)', 100000, 'Urologist + Assistant + Anesthetist'),
        ('Nephrectomy', 150000, 'Urologist + Assistant + Anesthetist'),
        ('Cystolithotomy (Bladder Stone Removal)', 70000, 'Urologist + Assistant + Anesthetist'),
        ('Ureteroscopy with Stone Removal', 90000, 'Urologist + Assistant + Anesthetist'),
        ('Circumcision', 20000, 'Urologist/Surgeon + Assistant'),
        ('Hydrocele Surgery', 35000, 'Urologist + Assistant'),
        ('Varicocelectomy', 45000, 'Urologist + Assistant + Anesthetist'),
        ('Vasectomy', 15000, 'Urologist + Assistant'),
    ],
    'Gastroenterology': [
        ('Appendectomy', 45000, 'General Surgeon + Assistant + Anesthetist'),
        ('Cholecystectomy (Open)', 65000, 'General Surgeon + Assistant + Anesthetist'),
        ('Cholecystectomy (Laparoscopic)', 90000, 'General Surgeon + Assistant + Anesthetist'),
        ('Hernia Repair (Inguinal)', 55000, 'General Surgeon + Assistant + Anesthetist'),
        ('Hernia Repair (Umbilical)', 45000, 'General Surgeon + Assistant + Anesthetist'),
        ('Bowel Resection & Anastomosis', 130000, 'General Surgeon + Assistant + Anesthetist'),
        ('Hemorrhoidectomy', 40000, 'General Surgeon + Assistant + Anesthetist'),
        ('Fistula-in-Ano Surgery', 45000, 'General Surgeon + Assistant + Anesthetist'),
        ('Partial Gastrectomy', 150000, 'General Surgeon + 2 Assistants + Anesthetist'),
        ('Colostomy/Ileostomy Formation', 70000, 'General Surgeon + Assistant + Anesthetist'),
    ],
    'Surgery': [
        ('Lipoma Excision', 15000, 'General Surgeon + Assistant'),
        ('Abscess Incision & Drainage', 10000, 'General Surgeon + Nurse'),
        ('Thyroid Nodule Excision', 75000, 'General Surgeon + Assistant + Anesthetist'),
        ('Breast Lump Excision', 45000, 'General Surgeon + Assistant + Anesthetist'),
        ('Mastectomy', 120000, 'General Surgeon + Assistant + Anesthetist'),
        ('Splenectomy', 130000, 'General Surgeon + Assistant + Anesthetist'),
        ('Sebaceous Cyst Excision', 12000, 'General Surgeon + Assistant'),
        ('Pilonidal Sinus Surgery', 40000, 'General Surgeon + Assistant + Anesthetist'),
    ],
    'Pediatrics': [
        ('Pediatric Hernia Repair', 40000, 'Pediatric Surgeon + Assistant + Anesthetist'),
        ('Pediatric Circumcision', 15000, 'Pediatric Surgeon + Assistant'),
        ('Pyloromyotomy', 60000, 'Pediatric Surgeon + Assistant + Anesthetist'),
        ('Pediatric Appendectomy', 45000, 'Pediatric Surgeon + Assistant + Anesthetist'),
        ('Undescended Testis Surgery', 50000, 'Pediatric Surgeon + Assistant + Anesthetist'),
        ('Pediatric Burn Surgery', 80000, 'Pediatric Surgeon + Assistant + Anesthetist'),
        ("Meckel's Diverticulectomy", 90000, 'Pediatric Surgeon + Assistant + Anesthetist'),
    ],
    'Gynecology': [
        ('Cesarean Section', 60000, 'Obstetrician + Assistant + Anesthetist + Nurse'),
        ('Hysterectomy (Abdominal)', 100000, 'Gynecologist + Assistant + Anesthetist'),
        ('Hysterectomy (Vaginal)', 90000, 'Gynecologist + Assistant + Anesthetist'),
        ('Dilation & Curettage (D&C)', 25000, 'Gynecologist + Assistant'),
        ('Ovarian Cystectomy', 70000, 'Gynecologist + Assistant + Anesthetist'),
        ('Myomectomy', 90000, 'Gynecologist + Assistant + Anesthetist'),
        ('Tubal Ligation', 30000, 'Gynecologist + Assistant + Anesthetist'),
        ('Ectopic Pregnancy Surgery', 80000, 'Gynecologist + Assistant + Anesthetist'),
        ('Vulval Surgery', 50000, 'Gynecologist + Assistant + Anesthetist'),
        ('Cervical Cerclage', 35000, 'Gynecologist + Assistant'),
    ],
    'Surgery ': [  # Transplant Surgery - trailing space keeps the dict key unique
        ('Kidney Transplant', 800000, 'Transplant Surgeon + 2 Assistants + Anesthetist + Nephrologist'),
        ('Bone Marrow Transplant', 900000, 'Hematologist + Transplant Team + Anesthetist'),
        ('Liver Transplant', 1200000, 'Transplant Surgeon + 2 Assistants + Anesthetist + Hepatologist'),
        ('Skin Transplant', 90000, 'Plastic Surgeon + Assistant + Anesthetist'),
        ('Pancreas Transplant', 950000, 'Transplant Surgeon + 2 Assistants + Anesthetist'),
    ],
}


def _distribute_price(base_price, index):
    """Small deterministic variance so identical-looking rows still differ slightly."""
    return round(base_price * (0.9 + 0.02 * (index % 6)), 2)


class Command(BaseCommand):
    help = (
        "Top up every module to the volumes required by the Final Requirements spec: "
        "100+ patients, 500+ medicines, 100+ lab tests, 100+ radiology tests, 100+ "
        "operations, 100+ billing items, insurance categories, extra beds, testimonials, "
        "and gallery images - all with English-transliterated Nepali names."
    )

    def add_arguments(self, parser):
        parser.add_argument('--patients', type=int, default=120, help='Target total patient count.')

    @transaction.atomic
    def handle(self, *args, **options):
        from patients.models import Patient, District, InsuranceCompany, InsuranceCategory
        from departments.models import Department
        from pharmacy.models import Medicine
        from laboratory.models import LabTest
        from radiology.models import RadiologyTest
        from operation_theatre.models import OperationType
        from admissions.models import Ward, Bed
        from website.models import Testimonial, GalleryImage, HospitalService

        if not District.objects.exists():
            self.stdout.write('Seeding Nepal address data first...')
            management.call_command('seed_nepal_address')
        if not Department.objects.exists():
            self.stdout.write('Seeding base departments/doctors first...')
            management.call_command('seed_demo_data')

        districts = list(District.objects.all())
        dept_by_name = {d.name: d for d in Department.objects.all()}

        # --- Patients --------------------------------------------------------
        target_total = options['patients']
        existing_count = Patient.objects.count()
        to_create = max(0, target_total - existing_count)
        created_patients = 0
        for i in range(to_create):
            is_male = i % 2 == 0
            first = random.choice(FIRST_NAMES_M if is_male else FIRST_NAMES_F)
            last = random.choice(LAST_NAMES)
            dob = datetime.date.today() - datetime.timedelta(days=random.randint(365 * 1, 365 * 80))
            years = (datetime.date.today() - dob).days // 365
            Patient.objects.create(
                first_name=first, last_name=last,
                gender=Patient.Gender.MALE if is_male else Patient.Gender.FEMALE,
                date_of_birth=dob, age_at_registration=f"{years} Years",
                phone_number=f"98{random.randint(10000000, 49999999)}",
                district=random.choice(districts),
                municipality=random.choice(['Kathmandu Metropolitan City', 'Pokhara Metropolitan City',
                                             'Bharatpur Metropolitan City', 'Biratnagar Metropolitan City',
                                             'Birgunj Metropolitan City', 'Dharan Sub-Metropolitan City']),
                ward_number=random.randint(1, 32), local_address=f"Tole {random.randint(1, 20)}",
                blood_group=random.choice([bg for bg, _ in Patient.BloodGroup.choices if bg]),
                occupation=random.choice(['Farmer', 'Teacher', 'Business', 'Driver', 'Student',
                                           'Housewife', 'Government Service', 'Shopkeeper', 'Laborer']),
            )
            created_patients += 1
        self.stdout.write(self.style.SUCCESS(
            f'{created_patients} new patients created ({Patient.objects.count()} total).'
        ))

        # --- Insurance companies + categories ---------------------------------
        company_defs = [
            ('Nepal Life Insurance', '01-4000000'), ('Prabhu Insurance', '01-4111111'),
            ('Shikhar Insurance', '01-4222222'), ('Sagarmatha Lumbini Insurance', '01-4333333'),
            ('IME Life Insurance', '01-4444444'), ('National Life Insurance', '01-4555555'),
            ('Rastriya Beema Sansthan', '01-4666666'),
        ]
        category_tiers = [('Bronze', 50), ('Silver', 70), ('Gold', 85), ('Government Employee', 100)]
        companies = []
        for name, phone in company_defs:
            company, _ = InsuranceCompany.objects.get_or_create(
                name=name, defaults={'contact_person': 'Claims Desk', 'phone_number': phone},
            )
            companies.append(company)
            for tier_name, pct in category_tiers:
                InsuranceCategory.objects.get_or_create(
                    company=company, name=tier_name, defaults={'coverage_percent': pct},
                )
        self.stdout.write(self.style.SUCCESS(
            f'{len(companies)} insurance companies with {len(category_tiers)} coverage tiers each ensured.'
        ))

        # --- Medicines (exactly 500 for the compact demo) -----------------------
        med_count = 0
        code_seq = Medicine.objects.count() + 1
        for gi, (generic, category, strengths, unit) in enumerate(GENERIC_DRUGS):
            for si, strength in enumerate(strengths):
                for bi, manufacturer in enumerate(MANUFACTURERS):
                    # Cap the catalog at 500: enough to demonstrate pharmacy search/stock
                    # without the unnecessary high-volume dummy catalog.
                    if Medicine.objects.count() >= 500:
                        break
                    if bi >= 6:
                        break
                    brand = f"{BRAND_PREFIXES[bi % len(BRAND_PREFIXES)]}-{generic.split()[0][:4].title()}{bi + 1}"
                    name = f"{generic} {strength}".strip()
                    unique_name = f"{name} ({brand})"
                    if Medicine.objects.filter(name=unique_name).exists():
                        continue
                    purchase = round(random.uniform(2, 60), 2)
                    selling = round(purchase * random.uniform(1.3, 1.8), 2)
                    Medicine.objects.create(
                        medicine_code=f"MED-{code_seq:05d}", name=unique_name, generic_name=generic,
                        brand_name=brand, category=category, strength=strength, unit=unit,
                        purchase_price=purchase, selling_price=selling,
                        current_stock=random.randint(50, 500), minimum_stock=20,
                        batch_number=f"B{random.randint(1000, 9999)}", manufacturer=manufacturer,
                        expiry_date=timezone.now().date() + datetime.timedelta(days=random.randint(180, 900)),
                    )
                    code_seq += 1
                    med_count += 1
        self.stdout.write(self.style.SUCCESS(f'{med_count} new medicines created ({Medicine.objects.count()} total).'))

        # --- Lab tests (100+) --------------------------------------------------
        lab_count = 0
        for name, sample_type, report_format, price in LAB_TESTS:
            dept = dept_by_name.get('Laboratory') or dept_by_name.get('Pathology')
            _, created = LabTest.objects.get_or_create(
                name=name, defaults={
                    'department': dept, 'sample_type': sample_type,
                    'price': price, 'report_format': report_format,
                },
            )
            lab_count += created
        self.stdout.write(self.style.SUCCESS(f'{lab_count} new lab tests created ({LabTest.objects.count()} total).'))

        # --- Radiology tests (100+) --------------------------------------------
        rad_dept = dept_by_name.get('Radiology')
        rad_defs = []
        for i, name in enumerate(XRAY_PARTS):
            rad_defs.append((f"X-Ray {name}", 300 + (i % 6) * 60, RadiologyTest.ReportType.IMAGING_REPORT))
        for i, name in enumerate(CONTRAST_STUDIES):
            rad_defs.append((f"Video X-Ray - {name}", 1800 + (i % 5) * 200, RadiologyTest.ReportType.IMAGING_REPORT))
        for i, name in enumerate(ULTRASOUND_TESTS):
            rad_defs.append((name, 900 + (i % 5) * 150, RadiologyTest.ReportType.SCAN_REPORT))
        for i, name in enumerate(CT_TESTS):
            rad_defs.append((name, 4000 + (i % 6) * 500, RadiologyTest.ReportType.SCAN_REPORT))
        for i, name in enumerate(MRI_TESTS):
            rad_defs.append((name, 8000 + (i % 6) * 1000, RadiologyTest.ReportType.SCAN_REPORT))
        for name in OTHER_RADIOLOGY:
            if 'Echo' in name:
                rtype = RadiologyTest.ReportType.ECHO_REPORT
            elif 'DEXA' in name:
                rtype = RadiologyTest.ReportType.DENSITY_REPORT
            elif 'ECG' in name:
                rtype = RadiologyTest.ReportType.ECG_STRIP
            else:
                rtype = RadiologyTest.ReportType.IMAGING_REPORT
            rad_defs.append((name, 1500, rtype))

        rad_count = 0
        for name, price, report_type in rad_defs:
            _, created = RadiologyTest.objects.get_or_create(
                name=name, defaults={'department': rad_dept, 'price': price, 'report_type': report_type},
            )
            rad_count += created
        self.stdout.write(self.style.SUCCESS(
            f'{rad_count} new radiology tests created ({RadiologyTest.objects.count()} total).'
        ))

        # --- Operation types (100+) ---------------------------------------------
        op_count = 0
        for dept_key, ops in OPERATIONS.items():
            dept = dept_by_name.get(dept_key.strip())
            for name, price, team in ops:
                _, created = OperationType.objects.get_or_create(
                    name=name, defaults={'department': dept, 'fixed_price': price, 'default_operating_team': team},
                )
                op_count += created
        self.stdout.write(self.style.SUCCESS(
            f'{op_count} new operation types created ({OperationType.objects.count()} total).'
        ))

        # --- General billing items / hospital services (100+ beyond catalogs) --
        general_services = [
            ('OPD Ticket', 'General OPD', 100), ('Emergency Ticket', 'Emergency', 500),
            ('Follow-up Visit', 'General OPD', 60), ('ICU Charge (Per Day)', 'ICU', 3000),
            ('General Bed Charge (Per Day)', 'General OPD', 800), ('Private Room Charge (Per Day)', 'General OPD', 2500),
            ('Oxygen Charge (Per Hour)', 'ICU', 150), ('Dressing Charge', 'Surgery', 200),
            ('Injection Charge', 'General OPD', 100), ('Nebulization Charge', 'Pulmonology', 150),
            ('Suturing Charge', 'Surgery', 500), ('Catheterization Charge', 'Urology', 400),
            ('IV Cannulation Charge', 'General OPD', 150), ('Ambulance Charge (Within City)', 'Emergency', 1000),
            ('Ambulance Charge (Outside City, Per KM)', 'Emergency', 50), ('Physiotherapy Session', 'Physiotherapy', 500),
            ('Dialysis Session', 'Nephrology', 3500), ('Endoscopy (Upper GI)', 'Gastroenterology', 3500),
            ('Colonoscopy', 'Gastroenterology', 5000), ('Vaccination - BCG', 'Pediatrics', 200),
            ('Vaccination - MMR', 'Pediatrics', 500), ('Vaccination - Hepatitis B', 'Pediatrics', 400),
            ('Health Checkup Package - Basic', 'General OPD', 2000), ('Health Checkup Package - Executive', 'General OPD', 5000),
            ('Death Certificate Charge', 'General OPD', 300), ('Medical Certificate Charge', 'General OPD', 200),
            ('Ward Boy / Attendant Charge (Per Day)', 'General OPD', 500), ('Nursing Care Charge (Per Day)', 'General OPD', 600),
            ('Discharge Summary Charge', 'General OPD', 150), ('Case File / Registration Charge', 'General OPD', 50),
        ]
        gs_count = 0
        seq = HospitalService.objects.filter(service_code__startswith='SVC-').count() + 1
        for name, dept_name, price in general_services:
            dept = dept_by_name.get(dept_name)
            code = f"SVC-{seq:04d}"
            _, created = HospitalService.objects.get_or_create(
                name=name, defaults={'service_code': code, 'department': dept, 'price': price},
            )
            if created:
                seq += 1
                gs_count += 1
        self.stdout.write(self.style.SUCCESS(
            f'{gs_count} new general billing items created ({HospitalService.objects.count()} total services).'
        ))

        # --- Beds/Wards (expand) -------------------------------------------------
        ward_defs = [
            ('General Ward A', Ward.WardType.GENERAL, 20), ('General Ward B', Ward.WardType.GENERAL, 20),
            ('ICU', Ward.WardType.ICU, 10), ('Private Ward', Ward.WardType.PRIVATE, 15),
            ('Emergency Ward', Ward.WardType.EMERGENCY, 10), ('Maternity Ward', Ward.WardType.MATERNITY, 15),
            ('Pediatric Ward', Ward.WardType.PEDIATRIC, 15),
        ]
        bed_count = 0
        for name, wtype, num_beds in ward_defs:
            ward, _ = Ward.objects.get_or_create(name=name, defaults={'ward_type': wtype})
            for bed_no in range(1, num_beds + 1):
                _, created = Bed.objects.get_or_create(ward=ward, bed_number=str(bed_no))
                bed_count += created
        self.stdout.write(self.style.SUCCESS(f'{bed_count} new beds created ({Bed.objects.count()} total beds).'))

        # --- Testimonials --------------------------------------------------------
        testimonial_msgs = [
            "The doctors and nurses took great care of me during my treatment.",
            "Very clean hospital with friendly staff. The billing process was quick and transparent.",
            "I appreciated how the Cash Counter explained my insurance coverage clearly.",
            "The emergency team saved my father's life. We are forever grateful.",
            "Registration was fast and the doctor explained everything patiently.",
            "The pharmacy had all my medicines in stock, no need to go elsewhere.",
            "The nursing staff checked on me every few hours during my admission.",
            "Great experience overall, would recommend this hospital to my family.",
            "The lab results were ready faster than expected.",
            "The operation theatre staff were very professional and reassuring.",
        ]
        testimonial_count = 0
        for i in range(20):
            is_male = i % 2 == 0
            name = f"{random.choice(FIRST_NAMES_M if is_male else FIRST_NAMES_F)} {random.choice(LAST_NAMES)}"
            _, created = Testimonial.objects.get_or_create(
                patient_name=name,
                defaults={'message': random.choice(testimonial_msgs), 'rating': random.choice([4, 5, 5, 5])},
            )
            testimonial_count += created
        self.stdout.write(self.style.SUCCESS(
            f'{testimonial_count} new testimonials created ({Testimonial.objects.count()} total).'
        ))

        # --- Gallery images (simple generated placeholder PNGs) ------------------
        gallery_titles = [
            'Hospital Main Building', 'Emergency Department', 'Operation Theatre', 'ICU Ward',
            'Reception & Registration Counter', 'Pharmacy Counter', 'Laboratory', 'Radiology Suite',
            'General Ward', 'Maternity Ward', 'Pediatric Ward', 'Ambulance Bay', 'Cafeteria',
            'Doctors Consultation Room', 'Hospital Garden',
        ]
        gallery_count = 0
        for i, title in enumerate(gallery_titles):
            if GalleryImage.objects.filter(title=title).exists():
                continue
            img_bytes = self._make_placeholder_png(title)
            gallery = GalleryImage(title=title, caption=f"{title} at {self._hospital_name()}", display_order=i)
            gallery.image.save(f"gallery_{slugify(title)}.png", ContentFile(img_bytes), save=False)
            gallery.save()
            gallery_count += 1
        self.stdout.write(self.style.SUCCESS(
            f'{gallery_count} new gallery images created ({GalleryImage.objects.count()} total).'
        ))

        self.stdout.write(self.style.SUCCESS('\nFinal requirements data seeding complete.'))

    def _hospital_name(self):
        from django.conf import settings
        return getattr(settings, 'HOSPITAL_NAME', 'the hospital')

    def _make_placeholder_png(self, label):
        """Generate a simple solid-color placeholder image with a caption using Pillow."""
        import io
        from PIL import Image, ImageDraw

        color = random.choice([(41, 128, 185), (39, 174, 96), (192, 57, 43), (142, 68, 173), (243, 156, 18)])
        img = Image.new('RGB', (800, 500), color=color)
        draw = ImageDraw.Draw(img)
        draw.rectangle([20, 20, 780, 480], outline=(255, 255, 255), width=4)
        draw.text((40, 230), label, fill=(255, 255, 255))
        buffer = io.BytesIO()
        img.save(buffer, format='PNG')
        return buffer.getvalue()
