# Generated by Django 5.0.14 on 2026-07-22 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('qualification', models.CharField(help_text='e.g. MBBS, MD (Cardiology)', max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('biography', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('available_days', models.CharField(blank=True, help_text='Comma-separated weekday codes, e.g. "mon,tue,wed,thu,fri"', max_length=40)),
                ('available_time_start', models.TimeField(blank=True, null=True)),
                ('available_time_end', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage "Featured Doctors"')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='departments.department')),
                ('user_account', models.OneToOneField(blank=True, help_text='Optional login account for this doctor (role must be "Doctor").', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctors_doctor',
                'ordering': ['full_name'],
            },
        ),
    ]
