# Generated by Django 5.0.14 on 2026-07-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacysale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('fonepay', 'FonePay'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('insurance', 'Insurance'), ('credit', 'Credit')], max_length=15),
        ),
    ]
